<?php

namespace Omnify\SsoClient\Models\OmnifyBase\Locales;

/**
 * Localized display names for Permission.
 *
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by @famgia/omnify-laravel
 */
class PermissionLocales
{
    /**
     * Localized display names for the model.
     *
     * @var array<string, string>
     */
    public const DISPLAY_NAMES = [
        'ja' => '権限',
        'en' => 'Permission',
        'vi' => 'Quyền hạn',
    ];

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    public const PROPERTY_DISPLAY_NAMES = [
        'name' => [
            'ja' => '権限名',
            'en' => 'Permission Name',
            'vi' => 'Tên quyền',
        ],
        'slug' => [
            'ja' => 'スラッグ',
            'en' => 'Slug',
            'vi' => 'Slug',
        ],
        'group' => [
            'ja' => 'グループ',
            'en' => 'Group',
            'vi' => 'Nhóm',
        ],
        'roles' => [
            'ja' => 'ロール',
            'en' => 'Roles',
            'vi' => 'Vai trò',
        ],
    ];
}
