<?php

namespace Omnify\SsoClient\Models\OmnifyBase\Locales;

/**
 * Localized display names for RolePermission.
 *
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by @famgia/omnify-laravel
 */
class RolePermissionLocales
{
    /**
     * Localized display names for the model.
     *
     * @var array<string, string>
     */
    public const DISPLAY_NAMES = [
        'ja' => 'ロール権限',
        'en' => 'Role Permission',
        'vi' => 'Quyền vai trò',
    ];

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    public const PROPERTY_DISPLAY_NAMES = [
        'role' => [
            'ja' => 'ロール',
            'en' => 'Role',
            'vi' => 'Vai trò',
        ],
        'permission' => [
            'ja' => '権限',
            'en' => 'Permission',
            'vi' => 'Quyền hạn',
        ],
    ];
}
