<?php

namespace Omnify\SsoClient\Models\OmnifyBase\Locales;

/**
 * Localized display names for Team.
 *
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by @famgia/omnify-laravel
 */
class TeamLocales
{
    /**
     * Localized display names for the model.
     *
     * @var array<string, string>
     */
    public const DISPLAY_NAMES = [
        'ja' => 'チーム',
        'en' => 'Team',
        'vi' => 'Nhóm',
    ];

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    public const PROPERTY_DISPLAY_NAMES = [
        'console_team_id' => [
            'ja' => 'Console Team ID',
            'en' => 'Console Team ID',
            'vi' => 'Console Team ID',
        ],
        'console_org_id' => [
            'ja' => 'Console Organization ID',
            'en' => 'Console Organization ID',
            'vi' => 'Console Organization ID',
        ],
        'name' => [
            'ja' => 'チーム名',
            'en' => 'Team Name',
            'vi' => 'Tên nhóm',
        ],
    ];
}
