/**
 * Form validation utilities for Ant Design + Zod
 * Generated by Omnify. You can customize this file.
 */

import type { RuleObject } from 'antd/es/form';
import type { z } from 'zod';
import { getZodMessage } from './zod-i18n.js';

/**
 * Convert Zod schema to Ant Design Form rule with i18n support
 *
 * @example
 * // Set locale once at component level
 * setZodLocale('ja');
 *
 * // Use without passing locale
 * <Form.Item
 *   name="email"
 *   rules={[zodRule(customerSchemas.email, 'メールアドレス')]}
 * >
 *   <Input />
 * </Form.Item>
 */
export function zodRule<T extends z.ZodTypeAny>(
  schema: T,
  displayName?: string
): RuleObject {
  const field = displayName ?? 'この項目';

  return {
    validator: async (_, value) => {
      // Empty check - treat as required
      if (value === undefined || value === null || value === '') {
        if (schema.safeParse(undefined).success) return;
        throw new Error(getZodMessage('required', { displayName: field }));
      }

      const result = schema.safeParse(value);
      if (result.success) return;

      // Get first Zod error
      const issue = result.error.issues[0];
      if (!issue) {
        throw new Error(getZodMessage('required', { displayName: field }));
      }

      // Translate based on error type
      switch (issue.code) {
        case 'too_small':
          if (issue.type === 'string' && issue.minimum === 1) {
            throw new Error(getZodMessage('required', { displayName: field }));
          }
          if (issue.type === 'string') {
            throw new Error(getZodMessage('minLength', { displayName: field, min: issue.minimum as number }));
          }
          throw new Error(getZodMessage('min', { displayName: field, min: issue.minimum as number }));

        case 'too_big':
          if (issue.type === 'string') {
            throw new Error(getZodMessage('maxLength', { displayName: field, max: issue.maximum as number }));
          }
          throw new Error(getZodMessage('max', { displayName: field, max: issue.maximum as number }));

        case 'invalid_string':
          if (issue.validation === 'email') {
            throw new Error(getZodMessage('email', { displayName: field }));
          }
          if (issue.validation === 'url') {
            throw new Error(getZodMessage('url', { displayName: field }));
          }
          if (issue.validation === 'regex') {
            throw new Error(getZodMessage('pattern', { displayName: field }));
          }
          break;

        case 'invalid_type':
          if (issue.received === 'undefined' || issue.received === 'null') {
            throw new Error(getZodMessage('required', { displayName: field }));
          }
          break;
      }

      // Fallback to Zod's original message
      throw new Error(issue.message);
    },
  };
}

/**
 * Create required rule with i18n message
 *
 * @example
 * <Form.Item
 *   name="name"
 *   rules={[requiredRule('名前')]}
 * >
 *   <Input />
 * </Form.Item>
 */
export function requiredRule(displayName: string): RuleObject {
  return {
    required: true,
    message: getZodMessage('required', { displayName }),
  };
}
