/**
 * Zod i18n - Localization for Zod validation messages
 * Generated by Omnify. You can customize this file.
 */

import { getMessage, defaultLocale } from '../schemas/i18n.js';

let currentLocale: string = defaultLocale;

/**
 * Set current locale for Zod validation messages
 */
export function setZodLocale(locale: string) {
  currentLocale = locale;
}

/**
 * Get current locale
 */
export function getZodLocale(): string {
  return currentLocale;
}

/**
 * Get translated validation message
 */
export function getZodMessage(
  key: string,
  params?: Record<string, string | number>
): string {
  return getMessage(key, currentLocale, params);
}
