<?php

namespace App\Support;

/**
 * Omnify Support Class
 *
 * Allows Laravel packages to register their schema directories.
 *
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @example
 * // In your package's ServiceProvider:
 * use App\Support\Omnify;
 *
 * public function boot()
 * {
 *     Omnify::addSchemaPath(__DIR__.'/../database/schemas');
 * }
 *
 * @generated by @famgia/omnify-laravel
 */
class Omnify
{
    /**
     * Registered schema paths from packages.
     *
     * @var array<array{path: string, namespace: string|null}>
     */
    protected static array $schemaPaths = [];

    /**
     * Register a schema directory path.
     *
     * @param string $path Absolute path to schema directory
     * @param string|null $namespace Optional namespace prefix for schemas
     * @return void
     */
    public static function addSchemaPath(string $path, ?string $namespace = null): void
    {
        $realPath = realpath($path);

        if ($realPath === false) {
            $realPath = $path;
        }

        static::$schemaPaths[] = [
            'path' => $realPath,
            'namespace' => $namespace,
        ];
    }

    /**
     * Get all registered schema paths.
     *
     * @return array<array{path: string, namespace: string|null}>
     */
    public static function getSchemaPaths(): array
    {
        return static::$schemaPaths;
    }

    /**
     * Clear all registered schema paths.
     */
    public static function clearSchemaPaths(): void
    {
        static::$schemaPaths = [];
    }

    /**
     * Export schema paths to JSON file for CLI consumption.
     *
     * @param string|null $outputPath Path to write JSON file
     * @return string Path to the generated file
     */
    public static function exportPaths(?string $outputPath = null): string
    {
        $outputPath = $outputPath ?? storage_path('omnify/schema-paths.json');

        $dir = dirname($outputPath);
        if (!is_dir($dir)) {
            mkdir($dir, 0755, true);
        }

        $data = [
            'generated_at' => date('c'),
            'paths' => static::$schemaPaths,
        ];

        file_put_contents($outputPath, json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));

        return $outputPath;
    }
}
