<?php

namespace App\Console\Commands;

use App\Support\Omnify;
use Illuminate\Console\Command;

/**
 * Sync registered schema paths for Omnify CLI.
 *
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by @famgia/omnify-laravel
 */
class OmnifySyncCommand extends Command
{
    protected $signature = 'omnify:sync {--output= : Custom output path}';

    protected $description = 'Export registered schema paths for Omnify CLI';

    public function handle(): int
    {
        $this->info('Syncing Omnify schema paths...');

        $paths = Omnify::getSchemaPaths();

        if (empty($paths)) {
            $this->warn('No additional schema paths registered.');
            $this->line('Tip: Packages can use Omnify::addSchemaPath()');
        } else {
            $this->line('Found ' . count($paths) . ' path(s):');
            foreach ($paths as $entry) {
                $ns = $entry['namespace'] ? " [{$entry['namespace']}]" : '';
                $this->line("  • {$entry['path']}{$ns}");
            }
        }

        $filePath = Omnify::exportPaths($this->option('output'));
        $this->info("✓ Exported to: {$filePath}");

        return Command::SUCCESS;
    }
}
