/**
 * Auto-generated validation rules and metadata for CacheLock.
 * DO NOT EDIT - This file is automatically generated and will be overwritten.
 */

export interface LocaleMap { [locale: string]: string; }

export interface ValidationRule {
  required?: boolean;
  type?: 'string' | 'number' | 'email' | 'url' | 'integer';
  min?: number;
  max?: number;
  len?: number;
  pattern?: RegExp;
  message: LocaleMap;
}

/** Display name for CacheLock */
export const CacheLockDisplayName: LocaleMap = {
  "ja": "キャッシュロック",
  "en": "Cache Lock"
};

/** Property display names for CacheLock */
export const CacheLockPropertyDisplayNames: Record<string, LocaleMap> = {
  key: {"ja":"キー","en":"Key"},
  owner: {"ja":"オーナー","en":"Owner"},
  expiration: {"ja":"有効期限","en":"Expiration"},
};

/** Validation rules for CacheLock (Ant Design compatible) */
export const CacheLockRules: Record<string, ValidationRule[]> = {
  key: [
    { required: true, message: {"ja":"キーは必須です","en":"Key is required"} },
  ],
  owner: [
    { required: true, message: {"ja":"オーナーは必須です","en":"Owner is required"} },
  ],
  expiration: [
    { required: true, message: {"ja":"有効期限は必須です","en":"Expiration is required"} },
  ],
};

/** Get validation rules with messages for a specific locale */
export function getCacheLockRules(locale: string): Record<string, Array<{ required?: boolean; type?: string; min?: number; max?: number; pattern?: RegExp; message: string }>> {
  const result: Record<string, Array<{ required?: boolean; type?: string; min?: number; max?: number; pattern?: RegExp; message: string }>> = {};
  for (const [prop, rules] of Object.entries(CacheLockRules)) {
    result[prop] = rules.map(rule => ({
      ...rule,
      message: rule.message[locale] ?? rule.message['en'] ?? '',
    }));
  }
  return result;
}

/** Get display name for a specific locale */
export function getCacheLockDisplayName(locale: string): string {
  return CacheLockDisplayName[locale] ?? CacheLockDisplayName['en'] ?? 'CacheLock';
}

/** Get property display name for a specific locale */
export function getCacheLockPropertyDisplayName(property: string, locale: string): string {
  const names = CacheLockPropertyDisplayNames[property];
  return names?.[locale] ?? names?.['en'] ?? property;
}
