/**
 * Auto-generated validation rules and metadata for Cache.
 * DO NOT EDIT - This file is automatically generated and will be overwritten.
 */

export interface LocaleMap { [locale: string]: string; }

export interface ValidationRule {
  required?: boolean;
  type?: 'string' | 'number' | 'email' | 'url' | 'integer';
  min?: number;
  max?: number;
  len?: number;
  pattern?: RegExp;
  message: LocaleMap;
}

/** Display name for Cache */
export const CacheDisplayName: LocaleMap = {
  "ja": "キャッシュ",
  "en": "Cache"
};

/** Property display names for Cache */
export const CachePropertyDisplayNames: Record<string, LocaleMap> = {
  key: {"ja":"キー","en":"Key"},
  value: {"ja":"値","en":"Value"},
  expiration: {"ja":"有効期限","en":"Expiration"},
};

/** Validation rules for Cache (Ant Design compatible) */
export const CacheRules: Record<string, ValidationRule[]> = {
  key: [
    { required: true, message: {"ja":"キーは必須です","en":"Key is required"} },
  ],
  value: [
    { required: true, message: {"ja":"値は必須です","en":"Value is required"} },
  ],
  expiration: [
    { required: true, message: {"ja":"有効期限は必須です","en":"Expiration is required"} },
  ],
};

/** Get validation rules with messages for a specific locale */
export function getCacheRules(locale: string): Record<string, Array<{ required?: boolean; type?: string; min?: number; max?: number; pattern?: RegExp; message: string }>> {
  const result: Record<string, Array<{ required?: boolean; type?: string; min?: number; max?: number; pattern?: RegExp; message: string }>> = {};
  for (const [prop, rules] of Object.entries(CacheRules)) {
    result[prop] = rules.map(rule => ({
      ...rule,
      message: rule.message[locale] ?? rule.message['en'] ?? '',
    }));
  }
  return result;
}

/** Get display name for a specific locale */
export function getCacheDisplayName(locale: string): string {
  return CacheDisplayName[locale] ?? CacheDisplayName['en'] ?? 'Cache';
}

/** Get property display name for a specific locale */
export function getCachePropertyDisplayName(property: string, locale: string): string {
  const names = CachePropertyDisplayNames[property];
  return names?.[locale] ?? names?.['en'] ?? property;
}
