/**
 * Auto-generated validation rules and metadata for FailedJob.
 * DO NOT EDIT - This file is automatically generated and will be overwritten.
 */

export interface LocaleMap { [locale: string]: string; }

export interface ValidationRule {
  required?: boolean;
  type?: 'string' | 'number' | 'email' | 'url' | 'integer';
  min?: number;
  max?: number;
  len?: number;
  pattern?: RegExp;
  message: LocaleMap;
}

/** Display name for FailedJob */
export const FailedJobDisplayName: LocaleMap = {
  "ja": "失敗したジョブ",
  "en": "Failed Job"
};

/** Property display names for FailedJob */
export const FailedJobPropertyDisplayNames: Record<string, LocaleMap> = {
  uuid: {"ja":"UUID","en":"UUID"},
  connection: {"ja":"接続","en":"Connection"},
  queue: {"ja":"キュー","en":"Queue"},
  payload: {"ja":"ペイロード","en":"Payload"},
  exception: {"ja":"例外","en":"Exception"},
  failed_at: {"ja":"失敗日時","en":"Failed At"},
};

/** Validation rules for FailedJob (Ant Design compatible) */
export const FailedJobRules: Record<string, ValidationRule[]> = {
  uuid: [
    { required: true, message: {"ja":"UUIDは必須です","en":"UUID is required"} },
  ],
  connection: [
    { required: true, message: {"ja":"接続は必須です","en":"Connection is required"} },
  ],
  queue: [
    { required: true, message: {"ja":"キューは必須です","en":"Queue is required"} },
  ],
  payload: [
    { required: true, message: {"ja":"ペイロードは必須です","en":"Payload is required"} },
  ],
  exception: [
    { required: true, message: {"ja":"例外は必須です","en":"Exception is required"} },
  ],
  failed_at: [
    { required: true, message: {"ja":"失敗日時は必須です","en":"Failed At is required"} },
  ],
};

/** Get validation rules with messages for a specific locale */
export function getFailedJobRules(locale: string): Record<string, Array<{ required?: boolean; type?: string; min?: number; max?: number; pattern?: RegExp; message: string }>> {
  const result: Record<string, Array<{ required?: boolean; type?: string; min?: number; max?: number; pattern?: RegExp; message: string }>> = {};
  for (const [prop, rules] of Object.entries(FailedJobRules)) {
    result[prop] = rules.map(rule => ({
      ...rule,
      message: rule.message[locale] ?? rule.message['en'] ?? '',
    }));
  }
  return result;
}

/** Get display name for a specific locale */
export function getFailedJobDisplayName(locale: string): string {
  return FailedJobDisplayName[locale] ?? FailedJobDisplayName['en'] ?? 'FailedJob';
}

/** Get property display name for a specific locale */
export function getFailedJobPropertyDisplayName(property: string, locale: string): string {
  const names = FailedJobPropertyDisplayNames[property];
  return names?.[locale] ?? names?.['en'] ?? property;
}
