/**
 * Auto-generated validation rules and metadata for Job.
 * DO NOT EDIT - This file is automatically generated and will be overwritten.
 */

export interface LocaleMap { [locale: string]: string; }

export interface ValidationRule {
  required?: boolean;
  type?: 'string' | 'number' | 'email' | 'url' | 'integer';
  min?: number;
  max?: number;
  len?: number;
  pattern?: RegExp;
  message: LocaleMap;
}

/** Display name for Job */
export const JobDisplayName: LocaleMap = {
  "ja": "ジョブ",
  "en": "Job"
};

/** Property display names for Job */
export const JobPropertyDisplayNames: Record<string, LocaleMap> = {
  queue: {"ja":"キュー","en":"Queue"},
  payload: {"ja":"ペイロード","en":"Payload"},
  attempts: {"ja":"試行回数","en":"Attempts"},
  reserved_at: {"ja":"予約日時","en":"Reserved At"},
  available_at: {"ja":"利用可能日時","en":"Available At"},
  created_at: {"ja":"作成日時","en":"Created At"},
};

/** Validation rules for Job (Ant Design compatible) */
export const JobRules: Record<string, ValidationRule[]> = {
  queue: [
    { required: true, message: {"ja":"キューは必須です","en":"Queue is required"} },
  ],
  payload: [
    { required: true, message: {"ja":"ペイロードは必須です","en":"Payload is required"} },
  ],
  attempts: [
    { required: true, message: {"ja":"試行回数は必須です","en":"Attempts is required"} },
  ],
  available_at: [
    { required: true, message: {"ja":"利用可能日時は必須です","en":"Available At is required"} },
  ],
  created_at: [
    { required: true, message: {"ja":"作成日時は必須です","en":"Created At is required"} },
  ],
};

/** Get validation rules with messages for a specific locale */
export function getJobRules(locale: string): Record<string, Array<{ required?: boolean; type?: string; min?: number; max?: number; pattern?: RegExp; message: string }>> {
  const result: Record<string, Array<{ required?: boolean; type?: string; min?: number; max?: number; pattern?: RegExp; message: string }>> = {};
  for (const [prop, rules] of Object.entries(JobRules)) {
    result[prop] = rules.map(rule => ({
      ...rule,
      message: rule.message[locale] ?? rule.message['en'] ?? '',
    }));
  }
  return result;
}

/** Get display name for a specific locale */
export function getJobDisplayName(locale: string): string {
  return JobDisplayName[locale] ?? JobDisplayName['en'] ?? 'Job';
}

/** Get property display name for a specific locale */
export function getJobPropertyDisplayName(property: string, locale: string): string {
  const names = JobPropertyDisplayNames[property];
  return names?.[locale] ?? names?.['en'] ?? property;
}
