/**
 * Auto-generated validation rules and metadata for JobBatch.
 * DO NOT EDIT - This file is automatically generated and will be overwritten.
 */

export interface LocaleMap { [locale: string]: string; }

export interface ValidationRule {
  required?: boolean;
  type?: 'string' | 'number' | 'email' | 'url' | 'integer';
  min?: number;
  max?: number;
  len?: number;
  pattern?: RegExp;
  message: LocaleMap;
}

/** Display name for JobBatch */
export const JobBatchDisplayName: LocaleMap = {
  "ja": "ジョブバッチ",
  "en": "Job Batch"
};

/** Property display names for JobBatch */
export const JobBatchPropertyDisplayNames: Record<string, LocaleMap> = {
  id: {"ja":"ID","en":"ID"},
  name: {"ja":"名前","en":"Name"},
  total_jobs: {"ja":"合計ジョブ数","en":"Total Jobs"},
  pending_jobs: {"ja":"保留中ジョブ数","en":"Pending Jobs"},
  failed_jobs: {"ja":"失敗ジョブ数","en":"Failed Jobs"},
  failed_job_ids: {"ja":"失敗ジョブID","en":"Failed Job IDs"},
  options: {"ja":"オプション","en":"Options"},
  cancelled_at: {"ja":"キャンセル日時","en":"Cancelled At"},
  created_at: {"ja":"作成日時","en":"Created At"},
  finished_at: {"ja":"完了日時","en":"Finished At"},
};

/** Validation rules for JobBatch (Ant Design compatible) */
export const JobBatchRules: Record<string, ValidationRule[]> = {
  id: [
    { required: true, message: {"ja":"IDは必須です","en":"ID is required"} },
  ],
  name: [
    { required: true, message: {"ja":"名前は必須です","en":"Name is required"} },
  ],
  total_jobs: [
    { required: true, message: {"ja":"合計ジョブ数は必須です","en":"Total Jobs is required"} },
  ],
  pending_jobs: [
    { required: true, message: {"ja":"保留中ジョブ数は必須です","en":"Pending Jobs is required"} },
  ],
  failed_jobs: [
    { required: true, message: {"ja":"失敗ジョブ数は必須です","en":"Failed Jobs is required"} },
  ],
  failed_job_ids: [
    { required: true, message: {"ja":"失敗ジョブIDは必須です","en":"Failed Job IDs is required"} },
  ],
  created_at: [
    { required: true, message: {"ja":"作成日時は必須です","en":"Created At is required"} },
  ],
};

/** Get validation rules with messages for a specific locale */
export function getJobBatchRules(locale: string): Record<string, Array<{ required?: boolean; type?: string; min?: number; max?: number; pattern?: RegExp; message: string }>> {
  const result: Record<string, Array<{ required?: boolean; type?: string; min?: number; max?: number; pattern?: RegExp; message: string }>> = {};
  for (const [prop, rules] of Object.entries(JobBatchRules)) {
    result[prop] = rules.map(rule => ({
      ...rule,
      message: rule.message[locale] ?? rule.message['en'] ?? '',
    }));
  }
  return result;
}

/** Get display name for a specific locale */
export function getJobBatchDisplayName(locale: string): string {
  return JobBatchDisplayName[locale] ?? JobBatchDisplayName['en'] ?? 'JobBatch';
}

/** Get property display name for a specific locale */
export function getJobBatchPropertyDisplayName(property: string, locale: string): string {
  const names = JobBatchPropertyDisplayNames[property];
  return names?.[locale] ?? names?.['en'] ?? property;
}
