/**
 * Auto-generated validation rules and metadata for PasswordResetToken.
 * DO NOT EDIT - This file is automatically generated and will be overwritten.
 */

export interface LocaleMap { [locale: string]: string; }

export interface ValidationRule {
  required?: boolean;
  type?: 'string' | 'number' | 'email' | 'url' | 'integer';
  min?: number;
  max?: number;
  len?: number;
  pattern?: RegExp;
  message: LocaleMap;
}

/** Display name for PasswordResetToken */
export const PasswordResetTokenDisplayName: LocaleMap = {
  "ja": "パスワードリセットトークン",
  "en": "Password Reset Token"
};

/** Property display names for PasswordResetToken */
export const PasswordResetTokenPropertyDisplayNames: Record<string, LocaleMap> = {
  email: {"ja":"メールアドレス","en":"Email"},
  token: {"ja":"トークン","en":"Token"},
  created_at: {"ja":"作成日時","en":"Created At"},
};

/** Validation rules for PasswordResetToken (Ant Design compatible) */
export const PasswordResetTokenRules: Record<string, ValidationRule[]> = {
  email: [
    { required: true, message: {"ja":"メールアドレスは必須です","en":"Email is required"} },
  ],
  token: [
    { required: true, message: {"ja":"トークンは必須です","en":"Token is required"} },
  ],
};

/** Get validation rules with messages for a specific locale */
export function getPasswordResetTokenRules(locale: string): Record<string, Array<{ required?: boolean; type?: string; min?: number; max?: number; pattern?: RegExp; message: string }>> {
  const result: Record<string, Array<{ required?: boolean; type?: string; min?: number; max?: number; pattern?: RegExp; message: string }>> = {};
  for (const [prop, rules] of Object.entries(PasswordResetTokenRules)) {
    result[prop] = rules.map(rule => ({
      ...rule,
      message: rule.message[locale] ?? rule.message['en'] ?? '',
    }));
  }
  return result;
}

/** Get display name for a specific locale */
export function getPasswordResetTokenDisplayName(locale: string): string {
  return PasswordResetTokenDisplayName[locale] ?? PasswordResetTokenDisplayName['en'] ?? 'PasswordResetToken';
}

/** Get property display name for a specific locale */
export function getPasswordResetTokenPropertyDisplayName(property: string, locale: string): string {
  const names = PasswordResetTokenPropertyDisplayNames[property];
  return names?.[locale] ?? names?.['en'] ?? property;
}
