/**
 * Auto-generated validation rules and metadata for PersonalAccessToken.
 * DO NOT EDIT - This file is automatically generated and will be overwritten.
 */

export interface LocaleMap { [locale: string]: string; }

export interface ValidationRule {
  required?: boolean;
  type?: 'string' | 'number' | 'email' | 'url' | 'integer';
  min?: number;
  max?: number;
  len?: number;
  pattern?: RegExp;
  message: LocaleMap;
}

/** Display name for PersonalAccessToken */
export const PersonalAccessTokenDisplayName: LocaleMap = {
  "ja": "個人アクセストークン",
  "en": "Personal Access Token"
};

/** Property display names for PersonalAccessToken */
export const PersonalAccessTokenPropertyDisplayNames: Record<string, LocaleMap> = {
  tokenable: {"ja":"トークン対象","en":"Tokenable"},
  name: {"ja":"名前","en":"Name"},
  token: {"ja":"トークン","en":"Token"},
  abilities: {"ja":"権限","en":"Abilities"},
  last_used_at: {"ja":"最終使用日時","en":"Last Used At"},
  expires_at: {"ja":"有効期限","en":"Expires At"},
};

/** Validation rules for PersonalAccessToken (Ant Design compatible) */
export const PersonalAccessTokenRules: Record<string, ValidationRule[]> = {
  tokenable: [
    { required: true, message: {"ja":"トークン対象は必須です","en":"Tokenable is required"} },
  ],
  name: [
    { required: true, message: {"ja":"名前は必須です","en":"Name is required"} },
  ],
  token: [
    { required: true, message: {"ja":"トークンは必須です","en":"Token is required"} },
    { max: 64, message: {"ja":"トークンは64文字以内で入力してください","en":"Token must be at most 64 characters"} },
  ],
};

/** Get validation rules with messages for a specific locale */
export function getPersonalAccessTokenRules(locale: string): Record<string, Array<{ required?: boolean; type?: string; min?: number; max?: number; pattern?: RegExp; message: string }>> {
  const result: Record<string, Array<{ required?: boolean; type?: string; min?: number; max?: number; pattern?: RegExp; message: string }>> = {};
  for (const [prop, rules] of Object.entries(PersonalAccessTokenRules)) {
    result[prop] = rules.map(rule => ({
      ...rule,
      message: rule.message[locale] ?? rule.message['en'] ?? '',
    }));
  }
  return result;
}

/** Get display name for a specific locale */
export function getPersonalAccessTokenDisplayName(locale: string): string {
  return PersonalAccessTokenDisplayName[locale] ?? PersonalAccessTokenDisplayName['en'] ?? 'PersonalAccessToken';
}

/** Get property display name for a specific locale */
export function getPersonalAccessTokenPropertyDisplayName(property: string, locale: string): string {
  const names = PersonalAccessTokenPropertyDisplayNames[property];
  return names?.[locale] ?? names?.['en'] ?? property;
}
