/**
 * Auto-generated validation rules and metadata for Session.
 * DO NOT EDIT - This file is automatically generated and will be overwritten.
 */

export interface LocaleMap { [locale: string]: string; }

export interface ValidationRule {
  required?: boolean;
  type?: 'string' | 'number' | 'email' | 'url' | 'integer';
  min?: number;
  max?: number;
  len?: number;
  pattern?: RegExp;
  message: LocaleMap;
}

/** Display name for Session */
export const SessionDisplayName: LocaleMap = {
  "ja": "セッション",
  "en": "Session"
};

/** Property display names for Session */
export const SessionPropertyDisplayNames: Record<string, LocaleMap> = {
  id: {"ja":"セッションID","en":"Session ID"},
  user_id: {"ja":"ユーザーID","en":"User ID"},
  ip_address: {"ja":"IPアドレス","en":"IP Address"},
  user_agent: {"ja":"ユーザーエージェント","en":"User Agent"},
  payload: {"ja":"ペイロード","en":"Payload"},
  last_activity: {"ja":"最終アクティビティ","en":"Last Activity"},
};

/** Validation rules for Session (Ant Design compatible) */
export const SessionRules: Record<string, ValidationRule[]> = {
  id: [
    { required: true, message: {"ja":"セッションIDは必須です","en":"Session ID is required"} },
  ],
  ip_address: [
    { max: 45, message: {"ja":"IPアドレスは45文字以内で入力してください","en":"IP Address must be at most 45 characters"} },
  ],
  payload: [
    { required: true, message: {"ja":"ペイロードは必須です","en":"Payload is required"} },
  ],
  last_activity: [
    { required: true, message: {"ja":"最終アクティビティは必須です","en":"Last Activity is required"} },
  ],
};

/** Get validation rules with messages for a specific locale */
export function getSessionRules(locale: string): Record<string, Array<{ required?: boolean; type?: string; min?: number; max?: number; pattern?: RegExp; message: string }>> {
  const result: Record<string, Array<{ required?: boolean; type?: string; min?: number; max?: number; pattern?: RegExp; message: string }>> = {};
  for (const [prop, rules] of Object.entries(SessionRules)) {
    result[prop] = rules.map(rule => ({
      ...rule,
      message: rule.message[locale] ?? rule.message['en'] ?? '',
    }));
  }
  return result;
}

/** Get display name for a specific locale */
export function getSessionDisplayName(locale: string): string {
  return SessionDisplayName[locale] ?? SessionDisplayName['en'] ?? 'Session';
}

/** Get property display name for a specific locale */
export function getSessionPropertyDisplayName(property: string, locale: string): string {
  const names = SessionPropertyDisplayNames[property];
  return names?.[locale] ?? names?.['en'] ?? property;
}
