/**
 * Auto-generated validation rules and metadata for User.
 * DO NOT EDIT - This file is automatically generated and will be overwritten.
 */

import type { LocaleMap, ValidationRule } from '../common.js';

/** Display name for User */
export const UserDisplayName: LocaleMap = {
  "ja": "ユーザー",
  "en": "User"
};

/** Property display names for User */
export const UserPropertyDisplayNames: Record<string, LocaleMap> = {
  name: {"ja":"名前","en":"Name"},
  email: {"ja":"メールアドレス","en":"Email"},
  email_verified_at: {"ja":"メール確認日時","en":"Email Verified At"},
  password: {"ja":"パスワード","en":"Password"},
  remember_token: {"ja":"リメンバートークン","en":"Remember Token"},
};

/** Validation rules for User (Ant Design compatible) */
export const UserRules: Record<string, ValidationRule[]> = {
  name: [
    { required: true, message: {"ja":"名前は必須です","en":"Name is required"} },
  ],
  email: [
    { required: true, message: {"ja":"メールアドレスは必須です","en":"Email is required"} },
  ],
  password: [
    { required: true, message: {"ja":"パスワードは必須です","en":"Password is required"} },
  ],
  remember_token: [
    { max: 100, message: {"ja":"リメンバートークンは100文字以内で入力してください","en":"Remember Token must be at most 100 characters"} },
  ],
};

/** Get validation rules with messages for a specific locale */
export function getUserRules(locale: string): Record<string, Array<{ required?: boolean; type?: string; min?: number; max?: number; pattern?: RegExp; message: string }>> {
  const result: Record<string, Array<{ required?: boolean; type?: string; min?: number; max?: number; pattern?: RegExp; message: string }>> = {};
  for (const [prop, rules] of Object.entries(UserRules)) {
    result[prop] = rules.map(rule => ({
      ...rule,
      message: rule.message[locale] ?? rule.message['en'] ?? '',
    }));
  }
  return result;
}

/** Get display name for a specific locale */
export function getUserDisplayName(locale: string): string {
  return UserDisplayName[locale] ?? UserDisplayName['en'] ?? 'User';
}

/** Get property display name for a specific locale */
export function getUserPropertyDisplayName(property: string, locale: string): string {
  const names = UserPropertyDisplayNames[property];
  return names?.[locale] ?? names?.['en'] ?? property;
}
