/**
 * Auto-generated TypeScript types from Omnify schemas.
 * DO NOT EDIT - This file is automatically generated and will be overwritten.
 */

/**
 * ユーザー
 */
export interface User {
  /** Primary key */
  readonly id: number;
  /** 名前 (Lastname) */
  readonly name_lastname: string;
  /** 名前 (Firstname) */
  readonly name_firstname: string;
  /** 名前 (KanaLastname) */
  readonly name_kana_lastname: string;
  /** 名前 (KanaFirstname) */
  readonly name_kana_firstname: string;
  /** 名前 (computed) */
  readonly name_full_name?: string | null;
  /** 名前 (computed) */
  readonly name_full_name_kana?: string | null;
  /** メールアドレス */
  readonly email: string;
  /** メール確認日時 */
  readonly email_verified_at?: string;
  /** パスワード */
  readonly password: string;
  /** リメンバートークン */
  readonly remember_token?: string;
  /** Creation timestamp */
  readonly created_at?: string;
  /** Last update timestamp */
  readonly updated_at?: string;
}
