/**
 * Auto-generated TypeScript types from Omnify schemas.
 * DO NOT EDIT - This file is automatically generated and will be overwritten.
 */

import type { DateTimeString } from '../common.js';

/**
 * ユーザー
 */
export interface User {
  /** Primary key */
  id: number;
  /** 名前 */
  name: string;
  /** メールアドレス */
  email: string;
  /** メール確認日時 */
  email_verified_at?: DateTimeString;
  /** パスワード */
  password: string;
  /** リメンバートークン */
  remember_token?: string;
  /** Creation timestamp */
  created_at?: DateTimeString;
  /** Last update timestamp */
  updated_at?: DateTimeString;
}

/** For creating new User (POST requests) */
export type UserCreate = Omit<User, 'id' | 'created_at' | 'updated_at'>;

/** For updating User (PUT/PATCH requests) */
export type UserUpdate = Partial<UserCreate>;
