/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 * KHÔNG ĐƯỢC SỬA FILE NÀY!
 *
 * Auto-generated TypeScript types from Omnify schemas.
 * Any manual changes will be OVERWRITTEN on next generation.
 *
 * To modify: Edit the schema YAML file and run: npx omnify generate
 */

import { z } from 'zod';
import type { DateTimeString } from '../common';
import type { Role } from './Role';

/**
 * 権限
 */
export interface Permission {
  /** Primary key */
  id: number;
  /** 権限名 */
  name: string;
  /** スラッグ */
  slug: string;
  /** グループ */
  group?: string;
  /** ロール */
  roles: Role[];
  /** Creation timestamp */
  created_at?: DateTimeString;
  /** Last update timestamp */
  updated_at?: DateTimeString;
}

// ============================================================================
// I18n (Internationalization)
// ============================================================================

/**
 * Unified i18n object for Permission
 * Contains model label and all field labels/placeholders
 */
export const permissionI18n = {
  /** Model display name */
  label: {"ja":"権限","en":"Permission","vi":"Quyền hạn"},
  /** Field labels and placeholders */
  fields: {
    name: {
      label: {"ja":"権限名","en":"Permission Name","vi":"Tên quyền"},
    },
    slug: {
      label: {"ja":"スラッグ","en":"Slug","vi":"Slug"},
    },
    group: {
      label: {"ja":"グループ","en":"Group","vi":"Nhóm"},
    },
    roles: {
      label: {"ja":"ロール","en":"Roles","vi":"Vai trò"},
    },
  },
} as const;

// ============================================================================
// Zod Schemas
// ============================================================================

/** Field schemas for Permission */
export const basePermissionSchemas = {
  name: z.string().min(1).max(100),
  slug: z.string().min(1).max(100),
  group: z.string().max(50).optional().nullable(),
} as const;

/** Create schema for Permission (POST requests) */
export const basePermissionCreateSchema = z.object({
  name: basePermissionSchemas.name,
  slug: basePermissionSchemas.slug,
  group: basePermissionSchemas.group,
});

/** Update schema for Permission (PUT/PATCH requests) */
export const basePermissionUpdateSchema = basePermissionCreateSchema.partial();

// ============================================================================
// Inferred Types
// ============================================================================

export type BasePermissionCreate = z.infer<typeof basePermissionCreateSchema>;
export type BasePermissionUpdate = z.infer<typeof basePermissionUpdateSchema>;

// ============================================================================
// I18n Helper Functions
// ============================================================================

/** Get model label for a specific locale */
export function getPermissionLabel(locale: string): string {
  return permissionI18n.label[locale as keyof typeof permissionI18n.label] ?? permissionI18n.label['en'] ?? 'Permission';
}

/** Get field label for a specific locale */
export function getPermissionFieldLabel(field: string, locale: string): string {
  const fieldI18n = permissionI18n.fields[field as keyof typeof permissionI18n.fields];
  if (!fieldI18n) return field;
  return fieldI18n.label[locale as keyof typeof fieldI18n.label] ?? fieldI18n.label['en'] ?? field;
}

/** Get field placeholder for a specific locale */
export function getPermissionFieldPlaceholder(field: string, locale: string): string {
  const fieldI18n = permissionI18n.fields[field as keyof typeof permissionI18n.fields];
  if (!fieldI18n || !('placeholder' in fieldI18n)) return '';
  const placeholder = fieldI18n.placeholder as Record<string, string>;
  return placeholder[locale] ?? placeholder['en'] ?? '';
}
