/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 * KHÔNG ĐƯỢC SỬA FILE NÀY!
 *
 * Auto-generated TypeScript types from Omnify schemas.
 * Any manual changes will be OVERWRITTEN on next generation.
 *
 * To modify: Edit the schema YAML file and run: npx omnify generate
 */

import { z } from 'zod';
import type { DateTimeString } from '../common';
import type { Permission } from './Permission';

/**
 * Role
 */
export interface Role {
  /** Primary key */
  id: number;
  /** Role Name */
  name: string;
  /** Slug */
  slug: string;
  /** Description */
  description?: string;
  /** Level */
  level: number;
  /** Permissions */
  permissions: Permission[];
  /** Creation timestamp */
  created_at?: DateTimeString;
  /** Last update timestamp */
  updated_at?: DateTimeString;
}

// ============================================================================
// I18n (Internationalization)
// ============================================================================

/**
 * Unified i18n object for Role
 * Contains model label and all field labels/placeholders
 */
export const roleI18n = {
  /** Model display name */
  label: {"en":"Role"},
  /** Field labels and placeholders */
  fields: {
    name: {
      label: {"en":"Role Name"},
    },
    slug: {
      label: {"en":"Slug"},
    },
    description: {
      label: {"en":"Description"},
    },
    level: {
      label: {"en":"Level"},
    },
    permissions: {
      label: {"en":"Permissions"},
    },
  },
} as const;

// ============================================================================
// Zod Schemas
// ============================================================================

/** Field schemas for Role */
export const baseRoleSchemas = {
  name: z.string().min(1).max(100),
  slug: z.string().min(1).max(100),
  description: z.string().optional().nullable(),
  level: z.number().int(),
} as const;

/** Create schema for Role (POST requests) */
export const baseRoleCreateSchema = z.object({
  name: baseRoleSchemas.name,
  slug: baseRoleSchemas.slug,
  description: baseRoleSchemas.description,
  level: baseRoleSchemas.level,
});

/** Update schema for Role (PUT/PATCH requests) */
export const baseRoleUpdateSchema = baseRoleCreateSchema.partial();

// ============================================================================
// Inferred Types
// ============================================================================

export type BaseRoleCreate = z.infer<typeof baseRoleCreateSchema>;
export type BaseRoleUpdate = z.infer<typeof baseRoleUpdateSchema>;

// ============================================================================
// I18n Helper Functions
// ============================================================================

/** Get model label for a specific locale */
export function getRoleLabel(locale: string): string {
  return roleI18n.label[locale as keyof typeof roleI18n.label] ?? roleI18n.label['en'] ?? 'Role';
}

/** Get field label for a specific locale */
export function getRoleFieldLabel(field: string, locale: string): string {
  const fieldI18n = roleI18n.fields[field as keyof typeof roleI18n.fields];
  if (!fieldI18n) return field;
  return fieldI18n.label[locale as keyof typeof fieldI18n.label] ?? fieldI18n.label['en'] ?? field;
}

/** Get field placeholder for a specific locale */
export function getRoleFieldPlaceholder(field: string, locale: string): string {
  const fieldI18n = roleI18n.fields[field as keyof typeof roleI18n.fields];
  if (!fieldI18n || !('placeholder' in fieldI18n)) return '';
  const placeholder = fieldI18n.placeholder as Record<string, string>;
  return placeholder[locale] ?? placeholder['en'] ?? '';
}
