/**
 * Auto-generated TypeScript types from Omnify schemas.
 * DO NOT EDIT - This file is automatically generated and will be overwritten.
 */

import { z } from 'zod';
import type { DateTimeString } from '../common';
import type { Permission } from './Permission';
import type { Role } from './Role';

/**
 * ロール権限
 */
export interface RolePermission {
  /** ロールID */
  role_id: number;
  /** 権限ID */
  permission_id: number;
  /** ロール */
  role: Role;
  /** 権限 */
  permission: Permission;
  /** Creation timestamp */
  created_at?: DateTimeString;
  /** Last update timestamp */
  updated_at?: DateTimeString;
}

// ============================================================================
// I18n (Internationalization)
// ============================================================================

/**
 * Unified i18n object for RolePermission
 * Contains model label and all field labels/placeholders
 */
export const rolePermissionI18n = {
  /** Model display name */
  label: {"ja":"ロール権限","en":"Role Permission","vi":"Role Permission"},
  /** Field labels and placeholders */
  fields: {
    role_id: {
      label: {"ja":"ロールID","en":"Role ID","vi":"Role ID"},
    },
    permission_id: {
      label: {"ja":"権限ID","en":"Permission ID","vi":"Permission ID"},
    },
    role: {
      label: {"ja":"ロール","en":"Role","vi":"Role"},
    },
    permission: {
      label: {"ja":"権限","en":"Permission","vi":"Permission"},
    },
  },
} as const;

// ============================================================================
// Zod Schemas
// ============================================================================

/** Field schemas for RolePermission */
export const baseRolePermissionSchemas = {
  role_id: z.number().int(),
  permission_id: z.number().int(),
} as const;

/** Create schema for RolePermission (POST requests) */
export const baseRolePermissionCreateSchema = z.object({
  role_id: baseRolePermissionSchemas.role_id,
  permission_id: baseRolePermissionSchemas.permission_id,
});

/** Update schema for RolePermission (PUT/PATCH requests) */
export const baseRolePermissionUpdateSchema = baseRolePermissionCreateSchema.partial();

// ============================================================================
// Inferred Types
// ============================================================================

export type BaseRolePermissionCreate = z.infer<typeof baseRolePermissionCreateSchema>;
export type BaseRolePermissionUpdate = z.infer<typeof baseRolePermissionUpdateSchema>;

// ============================================================================
// I18n Helper Functions
// ============================================================================

/** Get model label for a specific locale */
export function getRolePermissionLabel(locale: string): string {
  return rolePermissionI18n.label[locale as keyof typeof rolePermissionI18n.label] ?? rolePermissionI18n.label['en'] ?? 'RolePermission';
}

/** Get field label for a specific locale */
export function getRolePermissionFieldLabel(field: string, locale: string): string {
  const fieldI18n = rolePermissionI18n.fields[field as keyof typeof rolePermissionI18n.fields];
  if (!fieldI18n) return field;
  return fieldI18n.label[locale as keyof typeof fieldI18n.label] ?? fieldI18n.label['en'] ?? field;
}

/** Get field placeholder for a specific locale */
export function getRolePermissionFieldPlaceholder(field: string, locale: string): string {
  const fieldI18n = rolePermissionI18n.fields[field as keyof typeof rolePermissionI18n.fields];
  if (!fieldI18n || !('placeholder' in fieldI18n)) return '';
  const placeholder = fieldI18n.placeholder as Record<string, string>;
  return placeholder[locale] ?? placeholder['en'] ?? '';
}
