/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 * KHÔNG ĐƯỢC SỬA FILE NÀY!
 *
 * Auto-generated TypeScript types from Omnify schemas.
 * Any manual changes will be OVERWRITTEN on next generation.
 *
 * To modify: Edit the schema YAML file and run: npx omnify generate
 */

import { z } from 'zod';
import type { DateTimeString } from '../common';
import type { Permission } from './Permission';
import type { Role } from './Role';

/**
 * Role Permission
 */
export interface RolePermission {
  /** Primary key */
  id: number;
  /** Role */
  role: Role;
  /** Permission */
  permission: Permission;
  /** Creation timestamp */
  created_at?: DateTimeString;
  /** Last update timestamp */
  updated_at?: DateTimeString;
}

// ============================================================================
// I18n (Internationalization)
// ============================================================================

/**
 * Unified i18n object for RolePermission
 * Contains model label and all field labels/placeholders
 */
export const rolePermissionI18n = {
  /** Model display name */
  label: {"en":"Role Permission"},
  /** Field labels and placeholders */
  fields: {
    role: {
      label: {"en":"Role"},
    },
    permission: {
      label: {"en":"Permission"},
    },
  },
} as const;

// ============================================================================
// Zod Schemas
// ============================================================================

/** Field schemas for RolePermission */
export const baseRolePermissionSchemas = {
} as const;

/** Create schema for RolePermission (POST requests) */
export const baseRolePermissionCreateSchema = z.object({
});

/** Update schema for RolePermission (PUT/PATCH requests) */
export const baseRolePermissionUpdateSchema = baseRolePermissionCreateSchema.partial();

// ============================================================================
// Inferred Types
// ============================================================================

export type BaseRolePermissionCreate = z.infer<typeof baseRolePermissionCreateSchema>;
export type BaseRolePermissionUpdate = z.infer<typeof baseRolePermissionUpdateSchema>;

// ============================================================================
// I18n Helper Functions
// ============================================================================

/** Get model label for a specific locale */
export function getRolePermissionLabel(locale: string): string {
  return rolePermissionI18n.label[locale as keyof typeof rolePermissionI18n.label] ?? rolePermissionI18n.label['en'] ?? 'RolePermission';
}

/** Get field label for a specific locale */
export function getRolePermissionFieldLabel(field: string, locale: string): string {
  const fieldI18n = rolePermissionI18n.fields[field as keyof typeof rolePermissionI18n.fields];
  if (!fieldI18n) return field;
  return fieldI18n.label[locale as keyof typeof fieldI18n.label] ?? fieldI18n.label['en'] ?? field;
}

/** Get field placeholder for a specific locale */
export function getRolePermissionFieldPlaceholder(field: string, locale: string): string {
  const fieldI18n = rolePermissionI18n.fields[field as keyof typeof rolePermissionI18n.fields];
  if (!fieldI18n || !('placeholder' in fieldI18n)) return '';
  const placeholder = fieldI18n.placeholder as Record<string, string>;
  return placeholder[locale] ?? placeholder['en'] ?? '';
}
