/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 * KHÔNG ĐƯỢC SỬA FILE NÀY!
 *
 * Auto-generated TypeScript types from Omnify schemas.
 * Any manual changes will be OVERWRITTEN on next generation.
 *
 * To modify: Edit the schema YAML file and run: npx omnify generate
 */

import { z } from 'zod';
import type { DateTimeString } from '../common';
import type { Permission } from './Permission';

/**
 * チーム権限
 */
export interface TeamPermission {
  /** Primary key */
  id: number;
  /** Console Team ID */
  console_team_id: number;
  /** Console Organization ID */
  console_org_id: number;
  /** 権限 */
  permission: Permission;
  /** Creation timestamp */
  created_at?: DateTimeString;
  /** Last update timestamp */
  updated_at?: DateTimeString;
  /** Soft delete timestamp */
  deleted_at?: DateTimeString;
}

// ============================================================================
// I18n (Internationalization)
// ============================================================================

/**
 * Unified i18n object for TeamPermission
 * Contains model label and all field labels/placeholders
 */
export const teamPermissionI18n = {
  /** Model display name */
  label: {"ja":"チーム権限","en":"Team Permission","vi":"Team Permission"},
  /** Field labels and placeholders */
  fields: {
    console_team_id: {
      label: {"ja":"Console Team ID","en":"Console Team ID","vi":"Console Team ID"},
    },
    console_org_id: {
      label: {"ja":"Console Organization ID","en":"Console Organization ID","vi":"Console Organization ID"},
    },
    permission: {
      label: {"ja":"権限","en":"Permission","vi":"Permission"},
    },
  },
} as const;

// ============================================================================
// Zod Schemas
// ============================================================================

/** Field schemas for TeamPermission */
export const baseTeamPermissionSchemas = {
  console_team_id: z.number().int(),
  console_org_id: z.number().int(),
} as const;

/** Create schema for TeamPermission (POST requests) */
export const baseTeamPermissionCreateSchema = z.object({
  console_team_id: baseTeamPermissionSchemas.console_team_id,
  console_org_id: baseTeamPermissionSchemas.console_org_id,
});

/** Update schema for TeamPermission (PUT/PATCH requests) */
export const baseTeamPermissionUpdateSchema = baseTeamPermissionCreateSchema.partial();

// ============================================================================
// Inferred Types
// ============================================================================

export type BaseTeamPermissionCreate = z.infer<typeof baseTeamPermissionCreateSchema>;
export type BaseTeamPermissionUpdate = z.infer<typeof baseTeamPermissionUpdateSchema>;

// ============================================================================
// I18n Helper Functions
// ============================================================================

/** Get model label for a specific locale */
export function getTeamPermissionLabel(locale: string): string {
  return teamPermissionI18n.label[locale as keyof typeof teamPermissionI18n.label] ?? teamPermissionI18n.label['en'] ?? 'TeamPermission';
}

/** Get field label for a specific locale */
export function getTeamPermissionFieldLabel(field: string, locale: string): string {
  const fieldI18n = teamPermissionI18n.fields[field as keyof typeof teamPermissionI18n.fields];
  if (!fieldI18n) return field;
  return fieldI18n.label[locale as keyof typeof fieldI18n.label] ?? fieldI18n.label['en'] ?? field;
}

/** Get field placeholder for a specific locale */
export function getTeamPermissionFieldPlaceholder(field: string, locale: string): string {
  const fieldI18n = teamPermissionI18n.fields[field as keyof typeof teamPermissionI18n.fields];
  if (!fieldI18n || !('placeholder' in fieldI18n)) return '';
  const placeholder = fieldI18n.placeholder as Record<string, string>;
  return placeholder[locale] ?? placeholder['en'] ?? '';
}
