/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 * KHÔNG ĐƯỢC SỬA FILE NÀY!
 *
 * Auto-generated TypeScript types from Omnify schemas.
 * Any manual changes will be OVERWRITTEN on next generation.
 *
 * To modify: Edit the schema YAML file and run: npx omnify generate
 */

import { z } from 'zod';
import type { DateTimeString } from '../common';

/**
 * Team
 */
export interface Team {
  /** Primary key */
  id: number;
  /** Console Team ID */
  console_team_id: number;
  /** Console Organization ID */
  console_org_id: number;
  /** Team Name */
  name: string;
  /** Creation timestamp */
  created_at?: DateTimeString;
  /** Last update timestamp */
  updated_at?: DateTimeString;
  /** Soft delete timestamp */
  deleted_at?: DateTimeString;
}

// ============================================================================
// I18n (Internationalization)
// ============================================================================

/**
 * Unified i18n object for Team
 * Contains model label and all field labels/placeholders
 */
export const teamI18n = {
  /** Model display name */
  label: {"en":"Team"},
  /** Field labels and placeholders */
  fields: {
    console_team_id: {
      label: {"en":"Console Team ID"},
    },
    console_org_id: {
      label: {"en":"Console Organization ID"},
    },
    name: {
      label: {"en":"Team Name"},
    },
  },
} as const;

// ============================================================================
// Zod Schemas
// ============================================================================

/** Field schemas for Team */
export const baseTeamSchemas = {
  console_team_id: z.number().int(),
  console_org_id: z.number().int(),
  name: z.string().min(1).max(100),
} as const;

/** Create schema for Team (POST requests) */
export const baseTeamCreateSchema = z.object({
  console_team_id: baseTeamSchemas.console_team_id,
  console_org_id: baseTeamSchemas.console_org_id,
  name: baseTeamSchemas.name,
});

/** Update schema for Team (PUT/PATCH requests) */
export const baseTeamUpdateSchema = baseTeamCreateSchema.partial();

// ============================================================================
// Inferred Types
// ============================================================================

export type BaseTeamCreate = z.infer<typeof baseTeamCreateSchema>;
export type BaseTeamUpdate = z.infer<typeof baseTeamUpdateSchema>;

// ============================================================================
// I18n Helper Functions
// ============================================================================

/** Get model label for a specific locale */
export function getTeamLabel(locale: string): string {
  return teamI18n.label[locale as keyof typeof teamI18n.label] ?? teamI18n.label['en'] ?? 'Team';
}

/** Get field label for a specific locale */
export function getTeamFieldLabel(field: string, locale: string): string {
  const fieldI18n = teamI18n.fields[field as keyof typeof teamI18n.fields];
  if (!fieldI18n) return field;
  return fieldI18n.label[locale as keyof typeof fieldI18n.label] ?? fieldI18n.label['en'] ?? field;
}

/** Get field placeholder for a specific locale */
export function getTeamFieldPlaceholder(field: string, locale: string): string {
  const fieldI18n = teamI18n.fields[field as keyof typeof teamI18n.fields];
  if (!fieldI18n || !('placeholder' in fieldI18n)) return '';
  const placeholder = fieldI18n.placeholder as Record<string, string>;
  return placeholder[locale] ?? placeholder['en'] ?? '';
}
