/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 * KHÔNG ĐƯỢC SỬA FILE NÀY!
 *
 * Auto-generated TypeScript types from Omnify schemas.
 * Any manual changes will be OVERWRITTEN on next generation.
 *
 * To modify: Edit the schema YAML file and run: npx omnify generate
 */

import { z } from 'zod';
import type { DateTimeString } from '../common';
import type { Role } from './Role';

/**
 * ユーザー
 */
export interface User {
  /** Primary key */
  id: number;
  /** Console User ID */
  console_user_id?: number;
  /** Console Access Token */
  console_access_token?: string;
  /** Console Refresh Token */
  console_refresh_token?: string;
  /** Console Token有効期限 */
  console_token_expires_at?: DateTimeString;
  /** ロール */
  role?: Role;
  /** 名前 */
  name: string;
  /** メールアドレス */
  email: string;
  /** メール確認日時 */
  email_verified_at?: DateTimeString;
  /** パスワード */
  password: string;
  /** リメンバートークン */
  remember_token?: string;
  /** Creation timestamp */
  created_at?: DateTimeString;
  /** Last update timestamp */
  updated_at?: DateTimeString;
}

// ============================================================================
// I18n (Internationalization)
// ============================================================================

/**
 * Unified i18n object for User
 * Contains model label and all field labels/placeholders
 */
export const userI18n = {
  /** Model display name */
  label: {"ja":"ユーザー","en":"User","vi":"User"},
  /** Field labels and placeholders */
  fields: {
    console_user_id: {
      label: {"ja":"Console User ID","en":"Console User ID","vi":"Console User ID"},
    },
    console_access_token: {
      label: {"ja":"Console Access Token","en":"Console Access Token","vi":"Console Access Token"},
    },
    console_refresh_token: {
      label: {"ja":"Console Refresh Token","en":"Console Refresh Token","vi":"Console Refresh Token"},
    },
    console_token_expires_at: {
      label: {"ja":"Console Token有効期限","en":"Console Token Expiry","vi":"Console Token Expiry"},
    },
    role: {
      label: {"ja":"ロール","en":"Role","vi":"Role"},
    },
    name: {
      label: {"ja":"名前","en":"Name","vi":"Name"},
    },
    email: {
      label: {"ja":"メールアドレス","en":"Email","vi":"Email"},
    },
    email_verified_at: {
      label: {"ja":"メール確認日時","en":"Email Verified At","vi":"Email Verified At"},
    },
    password: {
      label: {"ja":"パスワード","en":"Password","vi":"Password"},
    },
    remember_token: {
      label: {"ja":"リメンバートークン","en":"Remember Token","vi":"Remember Token"},
    },
  },
} as const;

// ============================================================================
// Zod Schemas
// ============================================================================

/** Field schemas for User */
export const baseUserSchemas = {
  console_user_id: z.number().int().optional().nullable(),
  console_access_token: z.string().optional().nullable(),
  console_refresh_token: z.string().optional().nullable(),
  console_token_expires_at: z.string().datetime({ offset: true }).optional().nullable(),
  name: z.string().min(1),
  email: z.string().min(1),
  email_verified_at: z.string().datetime({ offset: true }).optional().nullable(),
  password: z.string().min(1),
  remember_token: z.string().max(100).optional().nullable(),
} as const;

/** Create schema for User (POST requests) */
export const baseUserCreateSchema = z.object({
  console_user_id: baseUserSchemas.console_user_id,
  console_access_token: baseUserSchemas.console_access_token,
  console_refresh_token: baseUserSchemas.console_refresh_token,
  console_token_expires_at: baseUserSchemas.console_token_expires_at,
  name: baseUserSchemas.name,
  email: baseUserSchemas.email,
  password: baseUserSchemas.password,
  remember_token: baseUserSchemas.remember_token,
});

/** Update schema for User (PUT/PATCH requests) */
export const baseUserUpdateSchema = baseUserCreateSchema.partial();

// ============================================================================
// Inferred Types
// ============================================================================

export type BaseUserCreate = z.infer<typeof baseUserCreateSchema>;
export type BaseUserUpdate = z.infer<typeof baseUserUpdateSchema>;

// ============================================================================
// I18n Helper Functions
// ============================================================================

/** Get model label for a specific locale */
export function getUserLabel(locale: string): string {
  return userI18n.label[locale as keyof typeof userI18n.label] ?? userI18n.label['en'] ?? 'User';
}

/** Get field label for a specific locale */
export function getUserFieldLabel(field: string, locale: string): string {
  const fieldI18n = userI18n.fields[field as keyof typeof userI18n.fields];
  if (!fieldI18n) return field;
  return fieldI18n.label[locale as keyof typeof fieldI18n.label] ?? fieldI18n.label['en'] ?? field;
}

/** Get field placeholder for a specific locale */
export function getUserFieldPlaceholder(field: string, locale: string): string {
  const fieldI18n = userI18n.fields[field as keyof typeof userI18n.fields];
  if (!fieldI18n || !('placeholder' in fieldI18n)) return '';
  const placeholder = fieldI18n.placeholder as Record<string, string>;
  return placeholder[locale] ?? placeholder['en'] ?? '';
}
