/**
 * Auto-generated TypeScript types from Omnify schemas.
 * DO NOT EDIT - This file is automatically generated and will be overwritten.
 */

import { z } from 'zod';
import type { DateTimeString } from '../common';

/**
 * ユーザー
 */
export interface User {
  /** Primary key */
  id: number;
  /** 名前 (Lastname) */
  name_lastname: string;
  /** 名前 (Firstname) */
  name_firstname: string;
  /** 名前 (KanaLastname) */
  name_kana_lastname?: string;
  /** 名前 (KanaFirstname) */
  name_kana_firstname?: string;
  /** 名前 (computed) */
  name_full_name?: string | null;
  /** 名前 (computed) */
  name_full_name_kana?: string | null;
  /** メールアドレス */
  email: string;
  /** メール確認日時 */
  email_verified_at?: DateTimeString;
  /** パスワード */
  password: string;
  /** リメンバートークン */
  remember_token?: string;
  /** Creation timestamp */
  created_at?: DateTimeString;
  /** Last update timestamp */
  updated_at?: DateTimeString;
}

// ============================================================================
// I18n (Internationalization)
// ============================================================================

/**
 * Unified i18n object for User
 * Contains model label and all field labels/placeholders
 */
export const userI18n = {
  /** Model display name */
  label: {"ja":"ユーザー","en":"User","vi":"User"},
  /** Field labels and placeholders */
  fields: {
    name: {
      label: {"ja":"名前","en":"Name","vi":"Name"},
    },
    name_lastname: {
      label: {"ja":"姓","en":"Last Name","vi":"Họ"},
      placeholder: {"ja":"例：山田","en":"e.g. Yamada","vi":"VD: Nguyễn"},
    },
    name_firstname: {
      label: {"ja":"名","en":"First Name","vi":"Tên"},
      placeholder: {"ja":"例：太郎","en":"e.g. Taro","vi":"VD: Văn A"},
    },
    name_kana_lastname: {
      label: {"ja":"姓（カナ）","en":"Last Name (Kana)","vi":"Họ (Kana)"},
      placeholder: {"ja":"例：ヤマダ","en":"e.g. Yamada (Katakana)","vi":"VD: Yamada (Katakana)"},
    },
    name_kana_firstname: {
      label: {"ja":"名（カナ）","en":"First Name (Kana)","vi":"Tên (Kana)"},
      placeholder: {"ja":"例：タロウ","en":"e.g. Taro (Katakana)","vi":"VD: Van A (Katakana)"},
    },
    email: {
      label: {"ja":"メールアドレス","en":"Email","vi":"Email"},
    },
    email_verified_at: {
      label: {"ja":"メール確認日時","en":"Email Verified At","vi":"Email Verified At"},
    },
    password: {
      label: {"ja":"パスワード","en":"Password","vi":"Password"},
    },
    remember_token: {
      label: {"ja":"リメンバートークン","en":"Remember Token","vi":"Remember Token"},
    },
  },
} as const;

// ============================================================================
// Zod Schemas
// ============================================================================

/** Field schemas for User */
export const baseUserSchemas = {
  /** Name (Lastname) */
  name_lastname: z.string().min(1).max(50),
  /** Name (Firstname) */
  name_firstname: z.string().min(1).max(50),
  /** Name (KanaLastname) */
  name_kana_lastname: z.string().max(100).regex(/^[ァ-ヶー・　]+$/).optional().nullable(),
  /** Name (KanaFirstname) */
  name_kana_firstname: z.string().max(100).regex(/^[ァ-ヶー・　]+$/).optional().nullable(),
  email: z.string().min(1),
  email_verified_at: z.string().datetime({ offset: true }).optional().nullable(),
  password: z.string().min(1),
  remember_token: z.string().max(100).optional().nullable(),
} as const;

/** Create schema for User (POST requests) */
export const baseUserCreateSchema = z.object({
  name_lastname: baseUserSchemas.name_lastname,
  name_firstname: baseUserSchemas.name_firstname,
  name_kana_lastname: baseUserSchemas.name_kana_lastname,
  name_kana_firstname: baseUserSchemas.name_kana_firstname,
  email: baseUserSchemas.email,
  password: baseUserSchemas.password,
  remember_token: baseUserSchemas.remember_token,
});

/** Update schema for User (PUT/PATCH requests) */
export const baseUserUpdateSchema = baseUserCreateSchema.partial();

// ============================================================================
// Inferred Types
// ============================================================================

export type BaseUserCreate = z.infer<typeof baseUserCreateSchema>;
export type BaseUserUpdate = z.infer<typeof baseUserUpdateSchema>;

// ============================================================================
// I18n Helper Functions
// ============================================================================

/** Get model label for a specific locale */
export function getUserLabel(locale: string): string {
  return userI18n.label[locale as keyof typeof userI18n.label] ?? userI18n.label['en'] ?? 'User';
}

/** Get field label for a specific locale */
export function getUserFieldLabel(field: string, locale: string): string {
  const fieldI18n = userI18n.fields[field as keyof typeof userI18n.fields];
  if (!fieldI18n) return field;
  return fieldI18n.label[locale as keyof typeof fieldI18n.label] ?? fieldI18n.label['en'] ?? field;
}

/** Get field placeholder for a specific locale */
export function getUserFieldPlaceholder(field: string, locale: string): string {
  const fieldI18n = userI18n.fields[field as keyof typeof userI18n.fields];
  if (!fieldI18n || !('placeholder' in fieldI18n)) return '';
  const placeholder = fieldI18n.placeholder as Record<string, string>;
  return placeholder[locale] ?? placeholder['en'] ?? '';
}
