<?php

/**
 * AUTO-GENERATED BY OMNIFY - DO NOT EDIT!
 *
 * This file is generated from Omnify schema: User
 * Re-run `npx omnify generate` to update.
 *
 * @generated
 */

namespace App\Http\Resources\OmnifyBase;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class UserResourceBase extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @return array<string, mixed>
     */
    protected function schemaArray(Request $request): array
    {
        return [
            'id' => $this->id,
            'name_lastname' => $this->name_lastname,
            'name_firstname' => $this->name_firstname,
            'name_kana_lastname' => $this->name_kana_lastname,
            'name_kana_firstname' => $this->name_kana_firstname,
            'name_full_name' => $this->name_full_name,
            'name_full_name_kana' => $this->name_full_name_kana,
            'email' => $this->email,
            'email_verified_at' => $this->email_verified_at?->toISOString(),
            'created_at' => $this->created_at?->toISOString(),
            'updated_at' => $this->updated_at?->toISOString(),
        ];
    }
}
