# =============================================================================
# Dev Script for Windows (PowerShell) - Omnify Tunnel Version
# Tunnel経由でlocalhostをインターネットに公開する
# =============================================================================

$ErrorActionPreference = "Stop"

# =============================================================================
# Tunnel Server設定
# =============================================================================
$TUNNEL_SERVER = "dev.omnify.jp"
$TUNNEL_PORT = 7000
$FRP_TOKEN = "65565cab2397330948c3374416a829dc1d0c25ad25055dd8d712b6d6555c9f36"

# =============================================================================
# 開発者名を取得/保存する関数
# =============================================================================
function Get-DevName {
    $configFile = ".omnify-dev"
    
    # ファイルから取得を試みる
    if (Test-Path $configFile) {
        $savedName = (Get-Content $configFile -Raw).Trim()
        if ($savedName) {
            return $savedName
        }
    }
    
    # ユーザーに入力を求める
    Write-Host ""
    Write-Host "" -ForegroundColor Cyan
    Write-Host " Developer name required" -ForegroundColor Yellow
    Write-Host "   This will be saved to .omnify-dev"
    Write-Host "   Example: satoshi, tanaka, yamada"
    Write-Host "" -ForegroundColor Cyan
    $devName = Read-Host "   Enter your dev name"
    
    # 入力検証
    if ([string]::IsNullOrWhiteSpace($devName)) {
        Write-Host " Dev name cannot be empty" -ForegroundColor Red
        exit 1
    }
    
    # 小文字に変換してスペースを削除
    $devName = $devName.ToLower().Replace(" ", "")
    
    # ファイルに保存
    $devName | Set-Content $configFile -NoNewline
    Write-Host "    Saved to .omnify-dev" -ForegroundColor Green
    Write-Host ""
    
    return $devName
}

# =============================================================================
# プロジェクト名を取得/保存する関数
# =============================================================================
function Get-ProjectName {
    $envFile = ".env"
    
    # .envファイルから取得を試みる
    if (Test-Path $envFile) {
        $content = Get-Content $envFile -Raw
        if ($content -match "OMNIFY_PROJECT_NAME=(.+)") {
            $savedName = $matches[1].Trim().Trim('"').Trim("'")
            if ($savedName) {
                return $savedName
            }
        }
    }
    
    # デフォルトはフォルダ名
    $defaultName = Split-Path -Leaf (Get-Location)
    
    # ユーザーに入力を求める
    Write-Host ""
    Write-Host "" -ForegroundColor Cyan
    Write-Host " Project name required" -ForegroundColor Yellow
    Write-Host "   This will be saved to .env file."
    Write-Host "   Press Enter to use default: $defaultName"
    Write-Host "" -ForegroundColor Cyan
    $projectName = Read-Host "   Enter project name [$defaultName]"
    
    # デフォルト値を使用
    if ([string]::IsNullOrWhiteSpace($projectName)) {
        $projectName = $defaultName
    }
    
    # 小文字に変換してスペースを削除
    $projectName = $projectName.ToLower().Replace(" ", "")
    
    # .envファイルに保存
    if (Test-Path $envFile) {
        $content = Get-Content $envFile -Raw
        if ($content -match "OMNIFY_PROJECT_NAME=") {
            $content = $content -replace "OMNIFY_PROJECT_NAME=.+", "OMNIFY_PROJECT_NAME=$projectName"
            $content | Set-Content $envFile -NoNewline
        } else {
            Add-Content $envFile "OMNIFY_PROJECT_NAME=$projectName"
        }
    } else {
        "OMNIFY_PROJECT_NAME=$projectName" | Set-Content $envFile
    }
    Write-Host "    Saved to .env" -ForegroundColor Green
    Write-Host ""
    
    return $projectName
}

# =============================================================================
# frpc設定ファイル生成関数
# =============================================================================
function New-FrpcConfig {
    param(
        [string]$DevName,
        [string]$ProjectName,
        [int]$FrontendPort
    )
    
    # ディレクトリ作成
    New-Item -ItemType Directory -Force -Path "./docker/frpc" | Out-Null
    
    # customDomainsを使用してフルドメインを指定（subdomainはドットをサポートしない）
    $config = @"
# Omnify Tunnel Client設定
# Auto-generated by dev.ps1

serverAddr = "$TUNNEL_SERVER"
serverPort = $TUNNEL_PORT

auth.method = "token"
auth.token = "$FRP_TOKEN"

# Frontend
[[proxies]]
name = "$ProjectName-$DevName-frontend"
type = "http"
localIP = "host.docker.internal"
localPort = $FrontendPort
customDomains = ["$ProjectName.$DevName.dev.omnify.jp"]

# Backend API
[[proxies]]
name = "$ProjectName-$DevName-api"
type = "http"
localIP = "backend"
localPort = 8000
customDomains = ["api.$ProjectName.$DevName.dev.omnify.jp"]

# phpMyAdmin
[[proxies]]
name = "$ProjectName-$DevName-phpmyadmin"
type = "http"
localIP = "phpmyadmin"
localPort = 80
customDomains = ["pma.$ProjectName.$DevName.dev.omnify.jp"]

# Mailpit
[[proxies]]
name = "$ProjectName-$DevName-mailpit"
type = "http"
localIP = "mailpit"
localPort = 8025
customDomains = ["mail.$ProjectName.$DevName.dev.omnify.jp"]

# MinIO S3 API
[[proxies]]
name = "$ProjectName-$DevName-minio"
type = "http"
localIP = "minio"
localPort = 9000
customDomains = ["s3.$ProjectName.$DevName.dev.omnify.jp"]

# MinIO Console
[[proxies]]
name = "$ProjectName-$DevName-minio-console"
type = "http"
localIP = "minio"
localPort = 9001
customDomains = ["minio.$ProjectName.$DevName.dev.omnify.jp"]

# Laravel Reverb (WebSocket)
[[proxies]]
name = "$ProjectName-$DevName-ws"
type = "http"
localIP = "reverb"
localPort = 8080
customDomains = ["ws.$ProjectName.$DevName.dev.omnify.jp"]

# Laravel Horizon
[[proxies]]
name = "$ProjectName-$DevName-horizon"
type = "http"
localIP = "backend"
localPort = 8000
customDomains = ["horizon.$ProjectName.$DevName.dev.omnify.jp"]
"@
    
    $config | Set-Content "./docker/frpc/frpc.toml" -Encoding UTF8
}

# =============================================================================
# 空きポートを見つける関数
# =============================================================================
function Find-AvailablePort {
    param([int]$StartPort)
    $port = $StartPort
    while (Get-NetTCPConnection -LocalPort $port -ErrorAction SilentlyContinue) {
        $port++
    }
    return $port
}

# =============================================================================
# メイン処理
# =============================================================================

# セットアップ確認
if (-not (Test-Path ".\backend") -or -not (Test-Path ".\frontend\package.json")) {
    Write-Host " Setup required. Run 'npm run setup' first." -ForegroundColor Red
    exit 1
}

Write-Host ""
Write-Host " Omnify Tunnel Development Environment" -ForegroundColor Cyan
Write-Host "" -ForegroundColor DarkGray
Write-Host ""

# 開発者名とプロジェクト名を取得
$DEV_NAME = Get-DevName
$PROJECT_NAME = Get-ProjectName

Write-Host " Developer: $DEV_NAME" -ForegroundColor White
Write-Host " Project:   $PROJECT_NAME" -ForegroundColor White
Write-Host ""

# フロントエンド用の空きポートを見つける
$FRONTEND_PORT = Find-AvailablePort -StartPort 3000

# =============================================================================
# Step 1: frpc設定ファイル生成
# =============================================================================
Write-Host "  Generating frpc config..." -ForegroundColor Yellow
New-FrpcConfig -DevName $DEV_NAME -ProjectName $PROJECT_NAME -FrontendPort $FRONTEND_PORT
Write-Host "    docker/frpc/frpc.toml" -ForegroundColor Green

# =============================================================================
# Step 2: docker-compose.ymlをコピー
# =============================================================================
Write-Host "  Generating docker-compose.yml..." -ForegroundColor Yellow
Copy-Item ".\docker\stubs\docker-compose.yml.stub" ".\docker-compose.yml" -Force
Write-Host "    docker-compose.yml" -ForegroundColor Green

# =============================================================================
# Step 3: Dockerサービスを起動
# =============================================================================
Write-Host ""
Write-Host " Starting Docker services..." -ForegroundColor Yellow
docker compose up -d mysql redis phpmyadmin mailpit minio backend reverb horizon frpc

# frpcの接続を待つ
Write-Host " Waiting for tunnel connection..." -ForegroundColor Yellow
Start-Sleep -Seconds 3

# =============================================================================
# Step 4: frontend .env.localを更新
# =============================================================================
$DOMAIN = "$PROJECT_NAME.$DEV_NAME.dev.omnify.jp"
$API_DOMAIN = "api.$PROJECT_NAME.$DEV_NAME.dev.omnify.jp"
$WS_DOMAIN = "ws.$PROJECT_NAME.$DEV_NAME.dev.omnify.jp"

@"
NEXT_PUBLIC_API_URL=https://$API_DOMAIN
NEXT_PUBLIC_REVERB_HOST=$WS_DOMAIN
NEXT_PUBLIC_REVERB_PORT=443
NEXT_PUBLIC_REVERB_SCHEME=https
NEXT_PUBLIC_REVERB_APP_KEY=omnify-reverb-key

# SSO Configuration (dev.console.omnify.jp)
NEXT_PUBLIC_SSO_CONSOLE_URL=https://dev.console.omnify.jp
NEXT_PUBLIC_SSO_SERVICE_SLUG=test-service
NEXT_PUBLIC_SSO_BASE_URL=https://$DOMAIN
"@ | Set-Content ".\frontend\.env.local" -Encoding UTF8

# =============================================================================
# 準備完了!
# =============================================================================
Write-Host ""
Write-Host "" -ForegroundColor Green
Write-Host " Tunnel Development Environment Ready!" -ForegroundColor Green
Write-Host "" -ForegroundColor Green
Write-Host ""
Write-Host "   Frontend:    https://$DOMAIN" -ForegroundColor Cyan
Write-Host "   API:         https://$API_DOMAIN" -ForegroundColor Cyan
Write-Host "   Horizon:     https://horizon.$PROJECT_NAME.$DEV_NAME.dev.omnify.jp" -ForegroundColor Cyan
Write-Host "   Telescope:   https://$API_DOMAIN/telescope" -ForegroundColor Cyan
Write-Host "   Pulse:       https://$API_DOMAIN/pulse" -ForegroundColor Cyan
Write-Host "   WebSocket:   wss://ws.$PROJECT_NAME.$DEV_NAME.dev.omnify.jp" -ForegroundColor Cyan
Write-Host "    phpMyAdmin:  https://pma.$PROJECT_NAME.$DEV_NAME.dev.omnify.jp" -ForegroundColor Cyan
Write-Host "   Mailpit:     https://mail.$PROJECT_NAME.$DEV_NAME.dev.omnify.jp" -ForegroundColor Cyan
Write-Host "   MinIO:       https://minio.$PROJECT_NAME.$DEV_NAME.dev.omnify.jp" -ForegroundColor Cyan
Write-Host ""
Write-Host "" -ForegroundColor DarkGray
Write-Host "  Starting frontend dev server..." -ForegroundColor Yellow
Write-Host "" -ForegroundColor DarkGray
Write-Host ""

# クリーンアップ: lockファイル削除
Remove-Item -Path ".\frontend\.next\dev\lock" -Force -ErrorAction SilentlyContinue

# フロントエンドdevサーバーを起動
Push-Location .\frontend
npm run dev -- -p $FRONTEND_PORT
Pop-Location
