<?php

namespace Omnify\SsoClient\Models\OmnifyBase;

/**
 * Base model class for all Omnify-generated models.
 * Contains model mapping for polymorphic relations.
 *
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by @famgia/omnify-laravel
 */

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\Relation;

abstract class BaseModel extends Model
{
    /**
     * Model class map for polymorphic relations.
     */
    protected static array $modelMap = [
        'User' => \Omnify\SsoClient\Models\User::class,
        'Permission' => \Omnify\SsoClient\Models\Permission::class,
        'Role' => \Omnify\SsoClient\Models\Role::class,
        'RolePermission' => \Omnify\SsoClient\Models\RolePermission::class,
        'Team' => \Omnify\SsoClient\Models\Team::class,
        'TeamPermission' => \Omnify\SsoClient\Models\TeamPermission::class,
    ];

    /**
     * Boot the model and register morph map.
     */
    protected static function boot(): void
    {
        parent::boot();

        // Register morph map for polymorphic relations
        Relation::enforceMorphMap(static::$modelMap);
    }

    /**
     * Get the model class for a given morph type.
     */
    public static function getModelClass(string $morphType): ?string
    {
        return static::$modelMap[$morphType] ?? null;
    }
}
