<?php

namespace Omnify\SsoClient\Models\OmnifyBase;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by @famgia/omnify-laravel
 */

use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\MorphTo;
use Illuminate\Database\Eloquent\Relations\MorphOne;
use Illuminate\Database\Eloquent\Relations\MorphMany;
use Illuminate\Database\Eloquent\Relations\MorphToMany;
use Illuminate\Database\Eloquent\Collection as EloquentCollection;
use Omnify\SsoClient\Models\OmnifyBase\Traits\HasLocalizedDisplayName;
use Omnify\SsoClient\Models\OmnifyBase\Locales\PermissionLocales;
use Omnify\SsoClient\Models\Role;

/**
 * PermissionBaseModel
 *
 * @property string $name
 * @property string $slug
 * @property string|null $group
 * @property \Illuminate\Database\Eloquent\Collection<Role> $roles
 */
class PermissionBaseModel extends BaseModel
{
    use HasLocalizedDisplayName;

    /**
     * The table associated with the model.
     */
    protected $table = 'permissions';

    /**
     * The primary key for the model.
     */
    protected $primaryKey = 'id';



    /**
     * Indicates if the model should be timestamped.
     */
    public $timestamps = true;

    /**
     * Localized display names for this model.
     *
     * @var array<string, string>
     */
    protected static array $localizedDisplayNames = PermissionLocales::DISPLAY_NAMES;

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    protected static array $localizedPropertyDisplayNames = PermissionLocales::PROPERTY_DISPLAY_NAMES;

    /**
     * The attributes that are mass assignable.
     */
    protected $fillable = [
        'name',
        'slug',
        'group',
    ];

    /**
     * The attributes that should be hidden for serialization.
     */
    protected $hidden = [

    ];

    /**
     * The accessors to append to the model's array form.
     */
    protected $appends = [

    ];

    /**
     * Get the attributes that should be cast.
     */
    protected function casts(): array
    {
        return [

        ];
    }

    /**
     * The roles that belong to this model.
     */
    public function roles(): BelongsToMany
    {
        return $this->belongsToMany(Role::class, 'role_permissions')
            ->withTimestamps();
    }
}
