<?php

namespace Omnify\SsoClient\Models\OmnifyBase;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by @famgia/omnify-laravel
 */

use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\MorphTo;
use Illuminate\Database\Eloquent\Relations\MorphOne;
use Illuminate\Database\Eloquent\Relations\MorphMany;
use Illuminate\Database\Eloquent\Relations\MorphToMany;
use Illuminate\Database\Eloquent\Collection as EloquentCollection;
use Omnify\SsoClient\Models\OmnifyBase\Traits\HasLocalizedDisplayName;
use Omnify\SsoClient\Models\OmnifyBase\Locales\TeamLocales;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * TeamBaseModel
 *
 * @property int $console_team_id
 * @property int $console_org_id
 * @property string $name
 */
class TeamBaseModel extends BaseModel
{
    use HasLocalizedDisplayName;
    use SoftDeletes;
    /**
     * The table associated with the model.
     */
    protected $table = 'teams';

    /**
     * The primary key for the model.
     */
    protected $primaryKey = 'id';



    /**
     * Indicates if the model should be timestamped.
     */
    public $timestamps = true;

    /**
     * Localized display names for this model.
     *
     * @var array<string, string>
     */
    protected static array $localizedDisplayNames = TeamLocales::DISPLAY_NAMES;

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    protected static array $localizedPropertyDisplayNames = TeamLocales::PROPERTY_DISPLAY_NAMES;

    /**
     * The attributes that are mass assignable.
     */
    protected $fillable = [
        'console_team_id',
        'console_org_id',
        'name',
    ];

    /**
     * The attributes that should be hidden for serialization.
     */
    protected $hidden = [

    ];

    /**
     * The accessors to append to the model's array form.
     */
    protected $appends = [

    ];

    /**
     * Get the attributes that should be cast.
     */
    protected function casts(): array
    {
        return [
            'console_team_id' => 'integer',
            'console_org_id' => 'integer',
        ];
    }


}
