<?php

/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 * KHÔNG ĐƯỢC SỬA FILE NÀY!
 *
 * This file is AUTO-GENERATED by Omnify from schema: TeamPermission
 * Any manual changes will be OVERWRITTEN on next generation.
 *
 * To modify: Edit the schema YAML file and run: npx omnify generate
 *
 * @generated by @famgia/omnify-laravel
 */

namespace App\Http\Requests\OmnifyBase;

use Illuminate\Foundation\Http\FormRequest;

abstract class TeamPermissionStoreRequestBase extends FormRequest
{
    /**
     * Validation rules generated from Omnify schema.
     *
     * Generated fields: console_org_id, console_team_id, permission_id
     *
     * @return array<string, array<int, mixed>>
     */
    protected function schemaRules(): array
    {
        return [
            'console_org_id' => ['required', 'integer'],
            'console_team_id' => ['required', 'integer'],
            'permission_id' => ['required', 'integer', 'exists:permissions,id'],
        ];
    }

    /**
     * Get custom attributes for validator errors.
     *
     * @return array<string, string>
     */
    protected function schemaAttributes(): array
    {
        return [
            'console_org_id' => 'Console Organization ID',
            'console_team_id' => 'Console Team ID',
            'permission_id' => 'Permission',
        ];
    }
}
