<?php

/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 * KHÔNG ĐƯỢC SỬA FILE NÀY!
 *
 * This file is AUTO-GENERATED by Omnify from schema: User
 * Any manual changes will be OVERWRITTEN on next generation.
 *
 * To modify: Edit the schema YAML file and run: npx omnify generate
 *
 * @generated by @famgia/omnify-laravel
 */

namespace App\Http\Requests\OmnifyBase;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

abstract class UserUpdateRequestBase extends FormRequest
{
    /**
     * Validation rules generated from Omnify schema.
     * All fields use 'sometimes' for partial updates.
     *
     * @return array<string, array<int, mixed>>
     */
    protected function schemaRules(): array
    {
        return [
            'name' => ['sometimes', 'string', 'max:255'],
            'email' => ['sometimes', 'string', 'max:255', Rule::unique('users')->ignore($this->route('user'))],
            'password' => ['sometimes', 'string', 'max:255'],
            'console_user_id' => ['sometimes', 'integer', Rule::unique('users')->ignore($this->route('user'))],
            'console_access_token' => ['sometimes', 'string'],
            'console_refresh_token' => ['sometimes', 'string'],
            'console_token_expires_at' => ['sometimes', 'date'],
            'role_id' => ['sometimes', 'integer', 'exists:roles,id'],
        ];
    }

    /**
     * Get custom attributes for validator errors.
     *
     * @return array<string, string>
     */
    protected function schemaAttributes(): array
    {
        return [
            'name' => 'Name',
            'email' => 'Email',
            'password' => 'Password',
            'console_user_id' => 'Console User ID',
            'console_access_token' => 'Console Access Token',
            'console_refresh_token' => 'Console Refresh Token',
            'console_token_expires_at' => 'Console Token Expiry',
            'role_id' => 'Role',
        ];
    }
}
