<?php

/**
 * AUTO-GENERATED BY OMNIFY - DO NOT EDIT!
 *
 * This file is generated from Omnify schema: User
 * Re-run `npx omnify generate` to update.
 *
 * @generated
 */

namespace App\Http\Requests\OmnifyBase;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

abstract class UserUpdateRequestBase extends FormRequest
{
    /**
     * Validation rules generated from Omnify schema.
     * All fields use 'sometimes' for partial updates.
     *
     * @return array<string, array<int, mixed>>
     */
    protected function schemaRules(): array
    {
        return [
            'name_lastname' => ['sometimes', 'string', 'max:50'],
            'name_firstname' => ['sometimes', 'string', 'max:50'],
            'name_kana_lastname' => ['sometimes', 'string', 'max:100', 'regex:/^[\x{30A0}-\x{30FF}\x{3000}-\x{303F}\x{FF00}-\x{FF9F}\s]+$/u'],
            'name_kana_firstname' => ['sometimes', 'string', 'max:100', 'regex:/^[\x{30A0}-\x{30FF}\x{3000}-\x{303F}\x{FF00}-\x{FF9F}\s]+$/u'],
            'email' => ['sometimes', 'string', 'max:255', Rule::unique('users')->ignore($this->route('user'))],
            'password' => ['sometimes', 'string', 'max:255'],
        ];
    }

    /**
     * Get custom attributes for validator errors.
     *
     * @return array<string, string>
     */
    protected function schemaAttributes(): array
    {
        return [
            'name_lastname' => 'name_lastname',
            'name_firstname' => 'name_firstname',
            'name_kana_lastname' => 'name_kana_lastname',
            'name_kana_firstname' => 'name_kana_firstname',
            'email' => 'Email',
            'password' => 'Password',
        ];
    }
}
