<?php

/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 * KHÔNG ĐƯỢC SỬA FILE NÀY!
 *
 * This file is AUTO-GENERATED by Omnify from schema: User
 * Any manual changes will be OVERWRITTEN on next generation.
 *
 * To modify: Edit the schema YAML file and run: npx omnify generate
 *
 * @generated by @famgia/omnify-laravel
 */

namespace App\Http\Requests\OmnifyBase;

use Illuminate\Foundation\Http\FormRequest;

abstract class UserStoreRequestBase extends FormRequest
{
    /**
     * Validation rules generated from Omnify schema.
     *
     * Generated fields: console_user_id, console_access_token, console_refresh_token, console_token_expires_at, role_id, name, email, password
     *
     * @return array<string, array<int, mixed>>
     */
    protected function schemaRules(): array
    {
        return [
            'console_user_id' => ['nullable', 'integer', 'unique:users'],
            'console_access_token' => ['nullable', 'string'],
            'console_refresh_token' => ['nullable', 'string'],
            'console_token_expires_at' => ['nullable', 'date'],
            'role_id' => ['nullable', 'integer', 'exists:roles,id'],
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'max:255', 'unique:users'],
            'password' => ['required', 'string', 'max:255'],
        ];
    }

    /**
     * Get custom attributes for validator errors.
     *
     * @return array<string, string>
     */
    protected function schemaAttributes(): array
    {
        return [
            'console_user_id' => 'Console User ID',
            'console_access_token' => 'Console Access Token',
            'console_refresh_token' => 'Console Refresh Token',
            'console_token_expires_at' => 'Console Token Expiry',
            'role_id' => 'Role',
            'name' => 'Name',
            'email' => 'Email',
            'password' => 'Password',
        ];
    }
}
