<?php

namespace App\Models\OmnifyBase;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by @famgia/omnify-laravel
 */

use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\MorphTo;
use Illuminate\Database\Eloquent\Relations\MorphOne;
use Illuminate\Database\Eloquent\Relations\MorphMany;
use Illuminate\Database\Eloquent\Relations\MorphToMany;
use Illuminate\Database\Eloquent\Collection as EloquentCollection;
use App\Models\OmnifyBase\Traits\HasLocalizedDisplayName;
use App\Models\OmnifyBase\Locales\UserLocales;


/**
 * UserBaseModel
 *
 * @property string $name_lastname
 * @property string $name_firstname
 * @property string $name_kana_lastname
 * @property string $name_kana_firstname
 * @property string $email
 * @property \Carbon\Carbon|null $email_verified_at
 * @property string $password
 * @property string|null $remember_token
 */
class UserBaseModel extends BaseModel
{
    use HasLocalizedDisplayName;

    /**
     * The table associated with the model.
     */
    protected $table = 'users';

    /**
     * The primary key for the model.
     */
    protected $primaryKey = 'id';



    /**
     * Indicates if the model should be timestamped.
     */
    public $timestamps = true;

    /**
     * Localized display names for this model.
     *
     * @var array<string, string>
     */
    protected static array $localizedDisplayNames = UserLocales::DISPLAY_NAMES;

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    protected static array $localizedPropertyDisplayNames = UserLocales::PROPERTY_DISPLAY_NAMES;

    /**
     * The attributes that are mass assignable.
     */
    protected $fillable = [
        'name_lastname',
        'name_firstname',
        'name_kana_lastname',
        'name_kana_firstname',
        'email',
        'email_verified_at',
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be hidden for serialization.
     */
    protected $hidden = [

    ];

    /**
     * The accessors to append to the model's array form.
     */
    protected $appends = [
        'name_full_name',
        'name_full_name_kana',
    ];

    /**
     * Get the attributes that should be cast.
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
        ];
    }

    /**
     * Get the full name attribute.
     */
    public function getNameFullNameAttribute(): ?string
    {
        $parts = array_filter([$this->name_lastname, $this->name_firstname], fn($v) => $v !== null && $v !== '');
        return count($parts) > 0 ? implode(' ', $parts) : null;
    }

    /**
     * Get the full name kana attribute.
     */
    public function getNameFullNameKanaAttribute(): ?string
    {
        $parts = array_filter([$this->name_kana_lastname, $this->name_kana_firstname], fn($v) => $v !== null && $v !== '');
        return count($parts) > 0 ? implode(' ', $parts) : null;
    }
}
