<?php

namespace App\Models\OmnifyBase;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by @famgia/omnify-laravel
 */

use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\MorphTo;
use Illuminate\Database\Eloquent\Relations\MorphOne;
use Illuminate\Database\Eloquent\Relations\MorphMany;
use Illuminate\Database\Eloquent\Relations\MorphToMany;
use Illuminate\Database\Eloquent\Collection as EloquentCollection;
use App\Models\OmnifyBase\Traits\HasLocalizedDisplayName;
use App\Models\OmnifyBase\Locales\UserLocales;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * UserBaseModel
 *
 * @property string $name
 * @property string $email
 * @property \Carbon\Carbon $email_verified_at
 * @property string $password
 * @property string $remember_token
 */
class UserBaseModel extends BaseModel
{
    use HasLocalizedDisplayName;
    use SoftDeletes;
    /**
     * The table associated with the model.
     */
    protected $table = 'users';

    /**
     * The primary key for the model.
     */
    protected $primaryKey = 'id';



    /**
     * Indicates if the model should be timestamped.
     */
    public $timestamps = true;

    /**
     * Localized display names for this model.
     *
     * @var array<string, string>
     */
    protected static array $localizedDisplayNames = UserLocales::DISPLAY_NAMES;

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    protected static array $localizedPropertyDisplayNames = UserLocales::PROPERTY_DISPLAY_NAMES;

    /**
     * The attributes that are mass assignable.
     */
    protected $fillable = [
        'name',
        'email',
        'email_verified_at',
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be hidden for serialization.
     */
    protected $hidden = [

    ];

    /**
     * The accessors to append to the model's array form.
     */
    protected $appends = [

    ];

    /**
     * Get the attributes that should be cast.
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
        ];
    }


}
