/**
 * Auto-generated TypeScript types from Omnify schemas.
 * DO NOT EDIT - This file is automatically generated and will be overwritten.
 */


/**
 * Locale map for multi-language support.
 */
export interface LocaleMap {
  [locale: string]: string;
}

/**
 * Supported locales in this project.
 */
export type Locale = 'ja' | 'en';

/**
 * Validation rule with multi-language messages.
 * Use get{Model}Rules(locale) to get Ant Design compatible rules.
 */
export interface ValidationRule {
  required?: boolean;
  type?: 'string' | 'number' | 'email' | 'url' | 'integer' | 'array' | 'object';
  min?: number;
  max?: number;
  len?: number;
  pattern?: RegExp;
  message: LocaleMap;
}

/**
 * ISO 8601 date-time string.
 */
export type DateTimeString = string;

/**
 * ISO 8601 date string (YYYY-MM-DD).
 */
export type DateString = string;
