/**
 * Auto-generated TypeScript types from Omnify schemas.
 * DO NOT EDIT - This file is automatically generated.
 */

// Interfaces
/**
 * User
 */
export interface User {
  /** Primary key */
  readonly id: number;
  /** Creation timestamp */
  readonly createdAt?: string;
  /** Last update timestamp */
  readonly updatedAt?: string;
  /** Soft delete timestamp */
  readonly deletedAt?: string;
}
