/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 * KHÔNG ĐƯỢC SỬA FILE NÀY!
 *
 * Auto-generated TypeScript types from Omnify schemas.
 * Any manual changes will be OVERWRITTEN on next generation.
 *
 * To modify: Edit the schema YAML file and run: npx omnify generate
 */

/**
 * 口座種別
 */
export enum BankAccountType {
  _1 = '1',
  _2 = '2',
  _4 = '4',
}

/** All BankAccountType values */
export const BankAccountTypeValues = Object.values(BankAccountType) as BankAccountType[];

/** Type guard for BankAccountType */
export function isBankAccountType(value: unknown): value is BankAccountType {
  return BankAccountTypeValues.includes(value as BankAccountType);
}

const bankAccountTypeLabels: Partial<Record<BankAccountType, Record<string, string>>> = {
  [BankAccountType._1]: { 'ja': '普通', 'en': 'Ordinary', 'vi': 'Thường', 'ko': '보통', 'zh-CN': '普通', 'zh-TW': '普通', 'th': 'ปกติ', 'es': 'Ordinario' },
  [BankAccountType._2]: { 'ja': '当座', 'en': 'Checking', 'vi': 'Thanh toán', 'ko': '당좌', 'zh-CN': '活期', 'zh-TW': '活期', 'th': 'กระแสรายวัน', 'es': 'Corriente' },
  [BankAccountType._4]: { 'ja': '貯蓄', 'en': 'Savings', 'vi': 'Tiết kiệm', 'ko': '저축', 'zh-CN': '储蓄', 'zh-TW': '儲蓄', 'th': 'ออมทรัพย์', 'es': 'Ahorro' },
};

/** Get label for BankAccountType value with locale support */
export function getBankAccountTypeLabel(value: BankAccountType, locale?: string): string {
  const labels = bankAccountTypeLabels[value];
  if (!labels) return value;
  if (locale && labels[locale]) return labels[locale];
  // Fallback: ja → en → first available
  return labels['ja'] ?? labels['en'] ?? Object.values(labels)[0] ?? value;
}

/** Get extra metadata for BankAccountType value (undefined if not defined) */
export function getBankAccountTypeExtra(_value: BankAccountType): Record<string, unknown> | undefined {
  return undefined;
}
