/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 * KHÔNG ĐƯỢC SỬA FILE NÀY!
 *
 * Auto-generated TypeScript types from Omnify schemas.
 * Any manual changes will be OVERWRITTEN on next generation.
 *
 * To modify: Edit the schema YAML file and run: npx omnify generate
 */

/**
 * 都道府県
 */
export enum Prefecture {
  Hokkaido = 'hokkaido',
  Aomori = 'aomori',
  Iwate = 'iwate',
  Miyagi = 'miyagi',
  Akita = 'akita',
  Yamagata = 'yamagata',
  Fukushima = 'fukushima',
  Ibaraki = 'ibaraki',
  Tochigi = 'tochigi',
  Gunma = 'gunma',
  Saitama = 'saitama',
  Chiba = 'chiba',
  Tokyo = 'tokyo',
  Kanagawa = 'kanagawa',
  Niigata = 'niigata',
  Toyama = 'toyama',
  Ishikawa = 'ishikawa',
  Fukui = 'fukui',
  Yamanashi = 'yamanashi',
  Nagano = 'nagano',
  Gifu = 'gifu',
  Shizuoka = 'shizuoka',
  Aichi = 'aichi',
  Mie = 'mie',
  Shiga = 'shiga',
  Kyoto = 'kyoto',
  Osaka = 'osaka',
  Hyogo = 'hyogo',
  Nara = 'nara',
  Wakayama = 'wakayama',
  Tottori = 'tottori',
  Shimane = 'shimane',
  Okayama = 'okayama',
  Hiroshima = 'hiroshima',
  Yamaguchi = 'yamaguchi',
  Tokushima = 'tokushima',
  Kagawa = 'kagawa',
  Ehime = 'ehime',
  Kochi = 'kochi',
  Fukuoka = 'fukuoka',
  Saga = 'saga',
  Nagasaki = 'nagasaki',
  Kumamoto = 'kumamoto',
  Oita = 'oita',
  Miyazaki = 'miyazaki',
  Kagoshima = 'kagoshima',
  Okinawa = 'okinawa',
}

/** All Prefecture values */
export const PrefectureValues = Object.values(Prefecture) as Prefecture[];

/** Type guard for Prefecture */
export function isPrefecture(value: unknown): value is Prefecture {
  return PrefectureValues.includes(value as Prefecture);
}

const prefectureLabels: Partial<Record<Prefecture, Record<string, string>>> = {
  [Prefecture.Hokkaido]: { 'ja': '北海道', 'en': 'Hokkaido', 'vi': 'Hokkaido', 'ko': '홋카이도', 'zh-CN': '北海道', 'zh-TW': '北海道', 'th': 'ฮอกไกโด', 'es': 'Hokkaido' },
  [Prefecture.Aomori]: { 'ja': '青森県', 'en': 'Aomori', 'vi': 'Aomori', 'ko': '아오모리현', 'zh-CN': '青森县', 'zh-TW': '青森縣', 'th': 'อาโอโมริ', 'es': 'Aomori' },
  [Prefecture.Iwate]: { 'ja': '岩手県', 'en': 'Iwate', 'vi': 'Iwate', 'ko': '이와테현', 'zh-CN': '岩手县', 'zh-TW': '岩手縣', 'th': 'อิวาเตะ', 'es': 'Iwate' },
  [Prefecture.Miyagi]: { 'ja': '宮城県', 'en': 'Miyagi', 'vi': 'Miyagi', 'ko': '미야기현', 'zh-CN': '宫城县', 'zh-TW': '宮城縣', 'th': 'มิยางิ', 'es': 'Miyagi' },
  [Prefecture.Akita]: { 'ja': '秋田県', 'en': 'Akita', 'vi': 'Akita', 'ko': '아키타현', 'zh-CN': '秋田县', 'zh-TW': '秋田縣', 'th': 'อากิตะ', 'es': 'Akita' },
  [Prefecture.Yamagata]: { 'ja': '山形県', 'en': 'Yamagata', 'vi': 'Yamagata', 'ko': '야마가타현', 'zh-CN': '山形县', 'zh-TW': '山形縣', 'th': 'ยามากาตะ', 'es': 'Yamagata' },
  [Prefecture.Fukushima]: { 'ja': '福島県', 'en': 'Fukushima', 'vi': 'Fukushima', 'ko': '후쿠시마현', 'zh-CN': '福岛县', 'zh-TW': '福島縣', 'th': 'ฟุกุชิมะ', 'es': 'Fukushima' },
  [Prefecture.Ibaraki]: { 'ja': '茨城県', 'en': 'Ibaraki', 'vi': 'Ibaraki', 'ko': '이바라키현', 'zh-CN': '茨城县', 'zh-TW': '茨城縣', 'th': 'อิบารากิ', 'es': 'Ibaraki' },
  [Prefecture.Tochigi]: { 'ja': '栃木県', 'en': 'Tochigi', 'vi': 'Tochigi', 'ko': '도치기현', 'zh-CN': '栃木县', 'zh-TW': '栃木縣', 'th': 'โทจิงิ', 'es': 'Tochigi' },
  [Prefecture.Gunma]: { 'ja': '群馬県', 'en': 'Gunma', 'vi': 'Gunma', 'ko': '군마현', 'zh-CN': '群马县', 'zh-TW': '群馬縣', 'th': 'กุนมะ', 'es': 'Gunma' },
  [Prefecture.Saitama]: { 'ja': '埼玉県', 'en': 'Saitama', 'vi': 'Saitama', 'ko': '사이타마현', 'zh-CN': '埼玉县', 'zh-TW': '埼玉縣', 'th': 'ไซตามะ', 'es': 'Saitama' },
  [Prefecture.Chiba]: { 'ja': '千葉県', 'en': 'Chiba', 'vi': 'Chiba', 'ko': '치바현', 'zh-CN': '千叶县', 'zh-TW': '千葉縣', 'th': 'จิบะ', 'es': 'Chiba' },
  [Prefecture.Tokyo]: { 'ja': '東京都', 'en': 'Tokyo', 'vi': 'Tokyo', 'ko': '도쿄도', 'zh-CN': '东京都', 'zh-TW': '東京都', 'th': 'โตเกียว', 'es': 'Tokio' },
  [Prefecture.Kanagawa]: { 'ja': '神奈川県', 'en': 'Kanagawa', 'vi': 'Kanagawa', 'ko': '가나가와현', 'zh-CN': '神奈川县', 'zh-TW': '神奈川縣', 'th': 'คานากาวะ', 'es': 'Kanagawa' },
  [Prefecture.Niigata]: { 'ja': '新潟県', 'en': 'Niigata', 'vi': 'Niigata', 'ko': '니가타현', 'zh-CN': '新潟县', 'zh-TW': '新潟縣', 'th': 'นีงาตะ', 'es': 'Niigata' },
  [Prefecture.Toyama]: { 'ja': '富山県', 'en': 'Toyama', 'vi': 'Toyama', 'ko': '도야마현', 'zh-CN': '富山县', 'zh-TW': '富山縣', 'th': 'โทยามะ', 'es': 'Toyama' },
  [Prefecture.Ishikawa]: { 'ja': '石川県', 'en': 'Ishikawa', 'vi': 'Ishikawa', 'ko': '이시카와현', 'zh-CN': '石川县', 'zh-TW': '石川縣', 'th': 'อิชิกาวะ', 'es': 'Ishikawa' },
  [Prefecture.Fukui]: { 'ja': '福井県', 'en': 'Fukui', 'vi': 'Fukui', 'ko': '후쿠이현', 'zh-CN': '福井县', 'zh-TW': '福井縣', 'th': 'ฟุกุอิ', 'es': 'Fukui' },
  [Prefecture.Yamanashi]: { 'ja': '山梨県', 'en': 'Yamanashi', 'vi': 'Yamanashi', 'ko': '야마나시현', 'zh-CN': '山梨县', 'zh-TW': '山梨縣', 'th': 'ยามานาชิ', 'es': 'Yamanashi' },
  [Prefecture.Nagano]: { 'ja': '長野県', 'en': 'Nagano', 'vi': 'Nagano', 'ko': '나가노현', 'zh-CN': '长野县', 'zh-TW': '長野縣', 'th': 'นากาโนะ', 'es': 'Nagano' },
  [Prefecture.Gifu]: { 'ja': '岐阜県', 'en': 'Gifu', 'vi': 'Gifu', 'ko': '기후현', 'zh-CN': '岐阜县', 'zh-TW': '岐阜縣', 'th': 'กิฟุ', 'es': 'Gifu' },
  [Prefecture.Shizuoka]: { 'ja': '静岡県', 'en': 'Shizuoka', 'vi': 'Shizuoka', 'ko': '시즈오카현', 'zh-CN': '静冈县', 'zh-TW': '靜岡縣', 'th': 'ชิซูโอกะ', 'es': 'Shizuoka' },
  [Prefecture.Aichi]: { 'ja': '愛知県', 'en': 'Aichi', 'vi': 'Aichi', 'ko': '아이치현', 'zh-CN': '爱知县', 'zh-TW': '愛知縣', 'th': 'ไอจิ', 'es': 'Aichi' },
  [Prefecture.Mie]: { 'ja': '三重県', 'en': 'Mie', 'vi': 'Mie', 'ko': '미에현', 'zh-CN': '三重县', 'zh-TW': '三重縣', 'th': 'มิเอะ', 'es': 'Mie' },
  [Prefecture.Shiga]: { 'ja': '滋賀県', 'en': 'Shiga', 'vi': 'Shiga', 'ko': '시가현', 'zh-CN': '滋贺县', 'zh-TW': '滋賀縣', 'th': 'ชิงะ', 'es': 'Shiga' },
  [Prefecture.Kyoto]: { 'ja': '京都府', 'en': 'Kyoto', 'vi': 'Kyoto', 'ko': '교토부', 'zh-CN': '京都府', 'zh-TW': '京都府', 'th': 'เกียวโต', 'es': 'Kioto' },
  [Prefecture.Osaka]: { 'ja': '大阪府', 'en': 'Osaka', 'vi': 'Osaka', 'ko': '오사카부', 'zh-CN': '大阪府', 'zh-TW': '大阪府', 'th': 'โอซากา', 'es': 'Osaka' },
  [Prefecture.Hyogo]: { 'ja': '兵庫県', 'en': 'Hyogo', 'vi': 'Hyogo', 'ko': '효고현', 'zh-CN': '兵库县', 'zh-TW': '兵庫縣', 'th': 'เฮียวโงะ', 'es': 'Hyogo' },
  [Prefecture.Nara]: { 'ja': '奈良県', 'en': 'Nara', 'vi': 'Nara', 'ko': '나라현', 'zh-CN': '奈良县', 'zh-TW': '奈良縣', 'th': 'นาระ', 'es': 'Nara' },
  [Prefecture.Wakayama]: { 'ja': '和歌山県', 'en': 'Wakayama', 'vi': 'Wakayama', 'ko': '와카야마현', 'zh-CN': '和歌山县', 'zh-TW': '和歌山縣', 'th': 'วากายามะ', 'es': 'Wakayama' },
  [Prefecture.Tottori]: { 'ja': '鳥取県', 'en': 'Tottori', 'vi': 'Tottori', 'ko': '돗토리현', 'zh-CN': '鸟取县', 'zh-TW': '鳥取縣', 'th': 'ท็อตโตริ', 'es': 'Tottori' },
  [Prefecture.Shimane]: { 'ja': '島根県', 'en': 'Shimane', 'vi': 'Shimane', 'ko': '시마네현', 'zh-CN': '岛根县', 'zh-TW': '島根縣', 'th': 'ชิมาเนะ', 'es': 'Shimane' },
  [Prefecture.Okayama]: { 'ja': '岡山県', 'en': 'Okayama', 'vi': 'Okayama', 'ko': '오카야마현', 'zh-CN': '冈山县', 'zh-TW': '岡山縣', 'th': 'โอคายามะ', 'es': 'Okayama' },
  [Prefecture.Hiroshima]: { 'ja': '広島県', 'en': 'Hiroshima', 'vi': 'Hiroshima', 'ko': '히로시마현', 'zh-CN': '广岛县', 'zh-TW': '廣島縣', 'th': 'ฮิโรชิมะ', 'es': 'Hiroshima' },
  [Prefecture.Yamaguchi]: { 'ja': '山口県', 'en': 'Yamaguchi', 'vi': 'Yamaguchi', 'ko': '야마구치현', 'zh-CN': '山口县', 'zh-TW': '山口縣', 'th': 'ยามากูจิ', 'es': 'Yamaguchi' },
  [Prefecture.Tokushima]: { 'ja': '徳島県', 'en': 'Tokushima', 'vi': 'Tokushima', 'ko': '도쿠시마현', 'zh-CN': '德岛县', 'zh-TW': '德島縣', 'th': 'โทกุชิมะ', 'es': 'Tokushima' },
  [Prefecture.Kagawa]: { 'ja': '香川県', 'en': 'Kagawa', 'vi': 'Kagawa', 'ko': '가가와현', 'zh-CN': '香川县', 'zh-TW': '香川縣', 'th': 'คากาวะ', 'es': 'Kagawa' },
  [Prefecture.Ehime]: { 'ja': '愛媛県', 'en': 'Ehime', 'vi': 'Ehime', 'ko': '에히메현', 'zh-CN': '爱媛县', 'zh-TW': '愛媛縣', 'th': 'เอฮิเมะ', 'es': 'Ehime' },
  [Prefecture.Kochi]: { 'ja': '高知県', 'en': 'Kochi', 'vi': 'Kochi', 'ko': '고치현', 'zh-CN': '高知县', 'zh-TW': '高知縣', 'th': 'โคจิ', 'es': 'Kochi' },
  [Prefecture.Fukuoka]: { 'ja': '福岡県', 'en': 'Fukuoka', 'vi': 'Fukuoka', 'ko': '후쿠오카현', 'zh-CN': '福冈县', 'zh-TW': '福岡縣', 'th': 'ฟุกุโอกะ', 'es': 'Fukuoka' },
  [Prefecture.Saga]: { 'ja': '佐賀県', 'en': 'Saga', 'vi': 'Saga', 'ko': '사가현', 'zh-CN': '佐贺县', 'zh-TW': '佐賀縣', 'th': 'ซางะ', 'es': 'Saga' },
  [Prefecture.Nagasaki]: { 'ja': '長崎県', 'en': 'Nagasaki', 'vi': 'Nagasaki', 'ko': '나가사키현', 'zh-CN': '长崎县', 'zh-TW': '長崎縣', 'th': 'นางาซากิ', 'es': 'Nagasaki' },
  [Prefecture.Kumamoto]: { 'ja': '熊本県', 'en': 'Kumamoto', 'vi': 'Kumamoto', 'ko': '구마모토현', 'zh-CN': '熊本县', 'zh-TW': '熊本縣', 'th': 'คุมาโมโตะ', 'es': 'Kumamoto' },
  [Prefecture.Oita]: { 'ja': '大分県', 'en': 'Oita', 'vi': 'Oita', 'ko': '오이타현', 'zh-CN': '大分县', 'zh-TW': '大分縣', 'th': 'โออิตะ', 'es': 'Oita' },
  [Prefecture.Miyazaki]: { 'ja': '宮崎県', 'en': 'Miyazaki', 'vi': 'Miyazaki', 'ko': '미야자키현', 'zh-CN': '宫崎县', 'zh-TW': '宮崎縣', 'th': 'มิยาซากิ', 'es': 'Miyazaki' },
  [Prefecture.Kagoshima]: { 'ja': '鹿児島県', 'en': 'Kagoshima', 'vi': 'Kagoshima', 'ko': '가고시마현', 'zh-CN': '鹿儿岛县', 'zh-TW': '鹿兒島縣', 'th': 'คาโกชิมะ', 'es': 'Kagoshima' },
  [Prefecture.Okinawa]: { 'ja': '沖縄県', 'en': 'Okinawa', 'vi': 'Okinawa', 'ko': '오키나와현', 'zh-CN': '冲绳县', 'zh-TW': '沖繩縣', 'th': 'โอกินาวะ', 'es': 'Okinawa' },
};

/** Get label for Prefecture value with locale support */
export function getPrefectureLabel(value: Prefecture, locale?: string): string {
  const labels = prefectureLabels[value];
  if (!labels) return value;
  if (locale && labels[locale]) return labels[locale];
  // Fallback: ja → en → first available
  return labels['ja'] ?? labels['en'] ?? Object.values(labels)[0] ?? value;
}

const prefectureExtra: Partial<Record<Prefecture, Record<string, unknown>>> = {
  [Prefecture.Hokkaido]: {"area":"hokkaido","code":1},
  [Prefecture.Aomori]: {"area":"tohoku","code":2},
  [Prefecture.Iwate]: {"area":"tohoku","code":3},
  [Prefecture.Miyagi]: {"area":"tohoku","code":4},
  [Prefecture.Akita]: {"area":"tohoku","code":5},
  [Prefecture.Yamagata]: {"area":"tohoku","code":6},
  [Prefecture.Fukushima]: {"area":"tohoku","code":7},
  [Prefecture.Ibaraki]: {"area":"kanto","code":8},
  [Prefecture.Tochigi]: {"area":"kanto","code":9},
  [Prefecture.Gunma]: {"area":"kanto","code":10},
  [Prefecture.Saitama]: {"area":"kanto","code":11},
  [Prefecture.Chiba]: {"area":"kanto","code":12},
  [Prefecture.Tokyo]: {"area":"kanto","code":13},
  [Prefecture.Kanagawa]: {"area":"kanto","code":14},
  [Prefecture.Niigata]: {"area":"chubu","code":15},
  [Prefecture.Toyama]: {"area":"chubu","code":16},
  [Prefecture.Ishikawa]: {"area":"chubu","code":17},
  [Prefecture.Fukui]: {"area":"chubu","code":18},
  [Prefecture.Yamanashi]: {"area":"chubu","code":19},
  [Prefecture.Nagano]: {"area":"chubu","code":20},
  [Prefecture.Gifu]: {"area":"chubu","code":21},
  [Prefecture.Shizuoka]: {"area":"chubu","code":22},
  [Prefecture.Aichi]: {"area":"chubu","code":23},
  [Prefecture.Mie]: {"area":"kinki","code":24},
  [Prefecture.Shiga]: {"area":"kinki","code":25},
  [Prefecture.Kyoto]: {"area":"kinki","code":26},
  [Prefecture.Osaka]: {"area":"kinki","code":27},
  [Prefecture.Hyogo]: {"area":"kinki","code":28},
  [Prefecture.Nara]: {"area":"kinki","code":29},
  [Prefecture.Wakayama]: {"area":"kinki","code":30},
  [Prefecture.Tottori]: {"area":"chugoku","code":31},
  [Prefecture.Shimane]: {"area":"chugoku","code":32},
  [Prefecture.Okayama]: {"area":"chugoku","code":33},
  [Prefecture.Hiroshima]: {"area":"chugoku","code":34},
  [Prefecture.Yamaguchi]: {"area":"chugoku","code":35},
  [Prefecture.Tokushima]: {"area":"shikoku","code":36},
  [Prefecture.Kagawa]: {"area":"shikoku","code":37},
  [Prefecture.Ehime]: {"area":"shikoku","code":38},
  [Prefecture.Kochi]: {"area":"shikoku","code":39},
  [Prefecture.Fukuoka]: {"area":"kyushu","code":40},
  [Prefecture.Saga]: {"area":"kyushu","code":41},
  [Prefecture.Nagasaki]: {"area":"kyushu","code":42},
  [Prefecture.Kumamoto]: {"area":"kyushu","code":43},
  [Prefecture.Oita]: {"area":"kyushu","code":44},
  [Prefecture.Miyazaki]: {"area":"kyushu","code":45},
  [Prefecture.Kagoshima]: {"area":"kyushu","code":46},
  [Prefecture.Okinawa]: {"area":"kyushu","code":47},
};

/** Get extra metadata for Prefecture value (undefined if not defined) */
export function getPrefectureExtra(value: Prefecture): Record<string, unknown> | undefined {
  return prefectureExtra[value];
}
