/**
 * Auto-generated TypeScript types from Omnify schemas.
 * DO NOT EDIT - This file is automatically generated and will be overwritten.
 */

/**
 * 都道府県コード
 */
export enum PrefectureCode {
  _1 = '1',
  _2 = '2',
  _3 = '3',
  _4 = '4',
  _5 = '5',
  _6 = '6',
  _7 = '7',
  _8 = '8',
  _9 = '9',
  _10 = '10',
  _11 = '11',
  _12 = '12',
  _13 = '13',
  _14 = '14',
  _15 = '15',
  _16 = '16',
  _17 = '17',
  _18 = '18',
  _19 = '19',
  _20 = '20',
  _21 = '21',
  _22 = '22',
  _23 = '23',
  _24 = '24',
  _25 = '25',
  _26 = '26',
  _27 = '27',
  _28 = '28',
  _29 = '29',
  _30 = '30',
  _31 = '31',
  _32 = '32',
  _33 = '33',
  _34 = '34',
  _35 = '35',
  _36 = '36',
  _37 = '37',
  _38 = '38',
  _39 = '39',
  _40 = '40',
  _41 = '41',
  _42 = '42',
  _43 = '43',
  _44 = '44',
  _45 = '45',
  _46 = '46',
  _47 = '47',
}

/** All PrefectureCode values */
export const PrefectureCodeValues = Object.values(PrefectureCode) as PrefectureCode[];

/** Type guard for PrefectureCode */
export function isPrefectureCode(value: unknown): value is PrefectureCode {
  return PrefectureCodeValues.includes(value as PrefectureCode);
}

const prefectureCodeLabels: Partial<Record<PrefectureCode, Record<string, string>>> = {
  [PrefectureCode._1]: { 'ja': '北海道', 'en': 'Hokkaido', 'vi': 'Hokkaido', 'ko': '홋카이도', 'zh-CN': '北海道', 'zh-TW': '北海道', 'th': 'ฮอกไกโด', 'es': 'Hokkaido' },
  [PrefectureCode._2]: { 'ja': '青森県', 'en': 'Aomori', 'vi': 'Aomori', 'ko': '아오모리현', 'zh-CN': '青森县', 'zh-TW': '青森縣', 'th': 'อาโอโมริ', 'es': 'Aomori' },
  [PrefectureCode._3]: { 'ja': '岩手県', 'en': 'Iwate', 'vi': 'Iwate', 'ko': '이와테현', 'zh-CN': '岩手县', 'zh-TW': '岩手縣', 'th': 'อิวาเตะ', 'es': 'Iwate' },
  [PrefectureCode._4]: { 'ja': '宮城県', 'en': 'Miyagi', 'vi': 'Miyagi', 'ko': '미야기현', 'zh-CN': '宫城县', 'zh-TW': '宮城縣', 'th': 'มิยางิ', 'es': 'Miyagi' },
  [PrefectureCode._5]: { 'ja': '秋田県', 'en': 'Akita', 'vi': 'Akita', 'ko': '아키타현', 'zh-CN': '秋田县', 'zh-TW': '秋田縣', 'th': 'อากิตะ', 'es': 'Akita' },
  [PrefectureCode._6]: { 'ja': '山形県', 'en': 'Yamagata', 'vi': 'Yamagata', 'ko': '야마가타현', 'zh-CN': '山形县', 'zh-TW': '山形縣', 'th': 'ยามากาตะ', 'es': 'Yamagata' },
  [PrefectureCode._7]: { 'ja': '福島県', 'en': 'Fukushima', 'vi': 'Fukushima', 'ko': '후쿠시마현', 'zh-CN': '福岛县', 'zh-TW': '福島縣', 'th': 'ฟุกุชิมะ', 'es': 'Fukushima' },
  [PrefectureCode._8]: { 'ja': '茨城県', 'en': 'Ibaraki', 'vi': 'Ibaraki', 'ko': '이바라키현', 'zh-CN': '茨城县', 'zh-TW': '茨城縣', 'th': 'อิบารากิ', 'es': 'Ibaraki' },
  [PrefectureCode._9]: { 'ja': '栃木県', 'en': 'Tochigi', 'vi': 'Tochigi', 'ko': '도치기현', 'zh-CN': '栃木县', 'zh-TW': '栃木縣', 'th': 'โทจิงิ', 'es': 'Tochigi' },
  [PrefectureCode._10]: { 'ja': '群馬県', 'en': 'Gunma', 'vi': 'Gunma', 'ko': '군마현', 'zh-CN': '群马县', 'zh-TW': '群馬縣', 'th': 'กุนมะ', 'es': 'Gunma' },
  [PrefectureCode._11]: { 'ja': '埼玉県', 'en': 'Saitama', 'vi': 'Saitama', 'ko': '사이타마현', 'zh-CN': '埼玉县', 'zh-TW': '埼玉縣', 'th': 'ไซตามะ', 'es': 'Saitama' },
  [PrefectureCode._12]: { 'ja': '千葉県', 'en': 'Chiba', 'vi': 'Chiba', 'ko': '치바현', 'zh-CN': '千叶县', 'zh-TW': '千葉縣', 'th': 'จิบะ', 'es': 'Chiba' },
  [PrefectureCode._13]: { 'ja': '東京都', 'en': 'Tokyo', 'vi': 'Tokyo', 'ko': '도쿄도', 'zh-CN': '东京都', 'zh-TW': '東京都', 'th': 'โตเกียว', 'es': 'Tokio' },
  [PrefectureCode._14]: { 'ja': '神奈川県', 'en': 'Kanagawa', 'vi': 'Kanagawa', 'ko': '가나가와현', 'zh-CN': '神奈川县', 'zh-TW': '神奈川縣', 'th': 'คานากาวะ', 'es': 'Kanagawa' },
  [PrefectureCode._15]: { 'ja': '新潟県', 'en': 'Niigata', 'vi': 'Niigata', 'ko': '니가타현', 'zh-CN': '新潟县', 'zh-TW': '新潟縣', 'th': 'นีงาตะ', 'es': 'Niigata' },
  [PrefectureCode._16]: { 'ja': '富山県', 'en': 'Toyama', 'vi': 'Toyama', 'ko': '도야마현', 'zh-CN': '富山县', 'zh-TW': '富山縣', 'th': 'โทยามะ', 'es': 'Toyama' },
  [PrefectureCode._17]: { 'ja': '石川県', 'en': 'Ishikawa', 'vi': 'Ishikawa', 'ko': '이시카와현', 'zh-CN': '石川县', 'zh-TW': '石川縣', 'th': 'อิชิกาวะ', 'es': 'Ishikawa' },
  [PrefectureCode._18]: { 'ja': '福井県', 'en': 'Fukui', 'vi': 'Fukui', 'ko': '후쿠이현', 'zh-CN': '福井县', 'zh-TW': '福井縣', 'th': 'ฟุกุอิ', 'es': 'Fukui' },
  [PrefectureCode._19]: { 'ja': '山梨県', 'en': 'Yamanashi', 'vi': 'Yamanashi', 'ko': '야마나시현', 'zh-CN': '山梨县', 'zh-TW': '山梨縣', 'th': 'ยามานาชิ', 'es': 'Yamanashi' },
  [PrefectureCode._20]: { 'ja': '長野県', 'en': 'Nagano', 'vi': 'Nagano', 'ko': '나가노현', 'zh-CN': '长野县', 'zh-TW': '長野縣', 'th': 'นากาโนะ', 'es': 'Nagano' },
  [PrefectureCode._21]: { 'ja': '岐阜県', 'en': 'Gifu', 'vi': 'Gifu', 'ko': '기후현', 'zh-CN': '岐阜县', 'zh-TW': '岐阜縣', 'th': 'กิฟุ', 'es': 'Gifu' },
  [PrefectureCode._22]: { 'ja': '静岡県', 'en': 'Shizuoka', 'vi': 'Shizuoka', 'ko': '시즈오카현', 'zh-CN': '静冈县', 'zh-TW': '靜岡縣', 'th': 'ชิซูโอกะ', 'es': 'Shizuoka' },
  [PrefectureCode._23]: { 'ja': '愛知県', 'en': 'Aichi', 'vi': 'Aichi', 'ko': '아이치현', 'zh-CN': '爱知县', 'zh-TW': '愛知縣', 'th': 'ไอจิ', 'es': 'Aichi' },
  [PrefectureCode._24]: { 'ja': '三重県', 'en': 'Mie', 'vi': 'Mie', 'ko': '미에현', 'zh-CN': '三重县', 'zh-TW': '三重縣', 'th': 'มิเอะ', 'es': 'Mie' },
  [PrefectureCode._25]: { 'ja': '滋賀県', 'en': 'Shiga', 'vi': 'Shiga', 'ko': '시가현', 'zh-CN': '滋贺县', 'zh-TW': '滋賀縣', 'th': 'ชิงะ', 'es': 'Shiga' },
  [PrefectureCode._26]: { 'ja': '京都府', 'en': 'Kyoto', 'vi': 'Kyoto', 'ko': '교토부', 'zh-CN': '京都府', 'zh-TW': '京都府', 'th': 'เกียวโต', 'es': 'Kioto' },
  [PrefectureCode._27]: { 'ja': '大阪府', 'en': 'Osaka', 'vi': 'Osaka', 'ko': '오사카부', 'zh-CN': '大阪府', 'zh-TW': '大阪府', 'th': 'โอซากา', 'es': 'Osaka' },
  [PrefectureCode._28]: { 'ja': '兵庫県', 'en': 'Hyogo', 'vi': 'Hyogo', 'ko': '효고현', 'zh-CN': '兵库县', 'zh-TW': '兵庫縣', 'th': 'เฮียวโงะ', 'es': 'Hyogo' },
  [PrefectureCode._29]: { 'ja': '奈良県', 'en': 'Nara', 'vi': 'Nara', 'ko': '나라현', 'zh-CN': '奈良县', 'zh-TW': '奈良縣', 'th': 'นาระ', 'es': 'Nara' },
  [PrefectureCode._30]: { 'ja': '和歌山県', 'en': 'Wakayama', 'vi': 'Wakayama', 'ko': '와카야마현', 'zh-CN': '和歌山县', 'zh-TW': '和歌山縣', 'th': 'วากายามะ', 'es': 'Wakayama' },
  [PrefectureCode._31]: { 'ja': '鳥取県', 'en': 'Tottori', 'vi': 'Tottori', 'ko': '돗토리현', 'zh-CN': '鸟取县', 'zh-TW': '鳥取縣', 'th': 'ท็อตโตริ', 'es': 'Tottori' },
  [PrefectureCode._32]: { 'ja': '島根県', 'en': 'Shimane', 'vi': 'Shimane', 'ko': '시마네현', 'zh-CN': '岛根县', 'zh-TW': '島根縣', 'th': 'ชิมาเนะ', 'es': 'Shimane' },
  [PrefectureCode._33]: { 'ja': '岡山県', 'en': 'Okayama', 'vi': 'Okayama', 'ko': '오카야마현', 'zh-CN': '冈山县', 'zh-TW': '岡山縣', 'th': 'โอคายามะ', 'es': 'Okayama' },
  [PrefectureCode._34]: { 'ja': '広島県', 'en': 'Hiroshima', 'vi': 'Hiroshima', 'ko': '히로시마현', 'zh-CN': '广岛县', 'zh-TW': '廣島縣', 'th': 'ฮิโรชิมะ', 'es': 'Hiroshima' },
  [PrefectureCode._35]: { 'ja': '山口県', 'en': 'Yamaguchi', 'vi': 'Yamaguchi', 'ko': '야마구치현', 'zh-CN': '山口县', 'zh-TW': '山口縣', 'th': 'ยามากูจิ', 'es': 'Yamaguchi' },
  [PrefectureCode._36]: { 'ja': '徳島県', 'en': 'Tokushima', 'vi': 'Tokushima', 'ko': '도쿠시마현', 'zh-CN': '德岛县', 'zh-TW': '德島縣', 'th': 'โทกุชิมะ', 'es': 'Tokushima' },
  [PrefectureCode._37]: { 'ja': '香川県', 'en': 'Kagawa', 'vi': 'Kagawa', 'ko': '가가와현', 'zh-CN': '香川县', 'zh-TW': '香川縣', 'th': 'คากาวะ', 'es': 'Kagawa' },
  [PrefectureCode._38]: { 'ja': '愛媛県', 'en': 'Ehime', 'vi': 'Ehime', 'ko': '에히메현', 'zh-CN': '爱媛县', 'zh-TW': '愛媛縣', 'th': 'เอฮิเมะ', 'es': 'Ehime' },
  [PrefectureCode._39]: { 'ja': '高知県', 'en': 'Kochi', 'vi': 'Kochi', 'ko': '고치현', 'zh-CN': '高知县', 'zh-TW': '高知縣', 'th': 'โคจิ', 'es': 'Kochi' },
  [PrefectureCode._40]: { 'ja': '福岡県', 'en': 'Fukuoka', 'vi': 'Fukuoka', 'ko': '후쿠오카현', 'zh-CN': '福冈县', 'zh-TW': '福岡縣', 'th': 'ฟุกุโอกะ', 'es': 'Fukuoka' },
  [PrefectureCode._41]: { 'ja': '佐賀県', 'en': 'Saga', 'vi': 'Saga', 'ko': '사가현', 'zh-CN': '佐贺县', 'zh-TW': '佐賀縣', 'th': 'ซางะ', 'es': 'Saga' },
  [PrefectureCode._42]: { 'ja': '長崎県', 'en': 'Nagasaki', 'vi': 'Nagasaki', 'ko': '나가사키현', 'zh-CN': '长崎县', 'zh-TW': '長崎縣', 'th': 'นางาซากิ', 'es': 'Nagasaki' },
  [PrefectureCode._43]: { 'ja': '熊本県', 'en': 'Kumamoto', 'vi': 'Kumamoto', 'ko': '구마모토현', 'zh-CN': '熊本县', 'zh-TW': '熊本縣', 'th': 'คุมาโมโตะ', 'es': 'Kumamoto' },
  [PrefectureCode._44]: { 'ja': '大分県', 'en': 'Oita', 'vi': 'Oita', 'ko': '오이타현', 'zh-CN': '大分县', 'zh-TW': '大分縣', 'th': 'โออิตะ', 'es': 'Oita' },
  [PrefectureCode._45]: { 'ja': '宮崎県', 'en': 'Miyazaki', 'vi': 'Miyazaki', 'ko': '미야자키현', 'zh-CN': '宫崎县', 'zh-TW': '宮崎縣', 'th': 'มิยาซากิ', 'es': 'Miyazaki' },
  [PrefectureCode._46]: { 'ja': '鹿児島県', 'en': 'Kagoshima', 'vi': 'Kagoshima', 'ko': '가고시마현', 'zh-CN': '鹿儿岛县', 'zh-TW': '鹿兒島縣', 'th': 'คาโกชิมะ', 'es': 'Kagoshima' },
  [PrefectureCode._47]: { 'ja': '沖縄県', 'en': 'Okinawa', 'vi': 'Okinawa', 'ko': '오키나와현', 'zh-CN': '冲绳县', 'zh-TW': '沖繩縣', 'th': 'โอกินาวะ', 'es': 'Okinawa' },
};

/** Get label for PrefectureCode value with locale support */
export function getPrefectureCodeLabel(value: PrefectureCode, locale?: string): string {
  const labels = prefectureCodeLabels[value];
  if (!labels) return value;
  if (locale && labels[locale]) return labels[locale];
  // Fallback: ja → en → first available
  return labels['ja'] ?? labels['en'] ?? Object.values(labels)[0] ?? value;
}

const prefectureCodeExtra: Partial<Record<PrefectureCode, Record<string, unknown>>> = {
  [PrefectureCode._1]: {"area":"hokkaido"},
  [PrefectureCode._2]: {"area":"tohoku"},
  [PrefectureCode._3]: {"area":"tohoku"},
  [PrefectureCode._4]: {"area":"tohoku"},
  [PrefectureCode._5]: {"area":"tohoku"},
  [PrefectureCode._6]: {"area":"tohoku"},
  [PrefectureCode._7]: {"area":"tohoku"},
  [PrefectureCode._8]: {"area":"kanto"},
  [PrefectureCode._9]: {"area":"kanto"},
  [PrefectureCode._10]: {"area":"kanto"},
  [PrefectureCode._11]: {"area":"kanto"},
  [PrefectureCode._12]: {"area":"kanto"},
  [PrefectureCode._13]: {"area":"kanto"},
  [PrefectureCode._14]: {"area":"kanto"},
  [PrefectureCode._15]: {"area":"chubu"},
  [PrefectureCode._16]: {"area":"chubu"},
  [PrefectureCode._17]: {"area":"chubu"},
  [PrefectureCode._18]: {"area":"chubu"},
  [PrefectureCode._19]: {"area":"chubu"},
  [PrefectureCode._20]: {"area":"chubu"},
  [PrefectureCode._21]: {"area":"chubu"},
  [PrefectureCode._22]: {"area":"chubu"},
  [PrefectureCode._23]: {"area":"chubu"},
  [PrefectureCode._24]: {"area":"kinki"},
  [PrefectureCode._25]: {"area":"kinki"},
  [PrefectureCode._26]: {"area":"kinki"},
  [PrefectureCode._27]: {"area":"kinki"},
  [PrefectureCode._28]: {"area":"kinki"},
  [PrefectureCode._29]: {"area":"kinki"},
  [PrefectureCode._30]: {"area":"kinki"},
  [PrefectureCode._31]: {"area":"chugoku"},
  [PrefectureCode._32]: {"area":"chugoku"},
  [PrefectureCode._33]: {"area":"chugoku"},
  [PrefectureCode._34]: {"area":"chugoku"},
  [PrefectureCode._35]: {"area":"chugoku"},
  [PrefectureCode._36]: {"area":"shikoku"},
  [PrefectureCode._37]: {"area":"shikoku"},
  [PrefectureCode._38]: {"area":"shikoku"},
  [PrefectureCode._39]: {"area":"shikoku"},
  [PrefectureCode._40]: {"area":"kyushu"},
  [PrefectureCode._41]: {"area":"kyushu"},
  [PrefectureCode._42]: {"area":"kyushu"},
  [PrefectureCode._43]: {"area":"kyushu"},
  [PrefectureCode._44]: {"area":"kyushu"},
  [PrefectureCode._45]: {"area":"kyushu"},
  [PrefectureCode._46]: {"area":"kyushu"},
  [PrefectureCode._47]: {"area":"kyushu"},
};

/** Get extra metadata for PrefectureCode value (undefined if not defined) */
export function getPrefectureCodeExtra(value: PrefectureCode): Record<string, unknown> | undefined {
  return prefectureCodeExtra[value];
}
