<?php

namespace Omnify\SsoClient\Models\OmnifyBase\Traits;

/**
 * Trait for localized display names.
 * Uses Laravel's app()->getLocale() for locale resolution.
 *
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by @famgia/omnify-laravel
 */
trait HasLocalizedDisplayName
{
    /**
     * Get the localized display name for this model.
     *
     * @param string|null $locale Locale code (defaults to app locale)
     * @return string
     */
    public static function displayName(?string $locale = null): string
    {
        $locale = $locale ?? app()->getLocale();
        $displayNames = static::$localizedDisplayNames ?? [];

        return $displayNames[$locale]
            ?? $displayNames[config('app.fallback_locale', 'en')]
            ?? $displayNames[array_key_first($displayNames) ?? 'en']
            ?? class_basename(static::class);
    }

    /**
     * Get all localized display names for this model.
     *
     * @return array<string, string>
     */
    public static function allDisplayNames(): array
    {
        return static::$localizedDisplayNames ?? [];
    }

    /**
     * Get the localized display name for a property.
     *
     * @param string $property Property name
     * @param string|null $locale Locale code (defaults to app locale)
     * @return string
     */
    public static function propertyDisplayName(string $property, ?string $locale = null): string
    {
        $locale = $locale ?? app()->getLocale();
        $displayNames = static::$localizedPropertyDisplayNames[$property] ?? [];

        return $displayNames[$locale]
            ?? $displayNames[config('app.fallback_locale', 'en')]
            ?? $displayNames[array_key_first($displayNames) ?? 'en']
            ?? $property;
    }

    /**
     * Get all localized display names for a property.
     *
     * @param string $property Property name
     * @return array<string, string>
     */
    public static function allPropertyDisplayNames(string $property): array
    {
        return static::$localizedPropertyDisplayNames[$property] ?? [];
    }

    /**
     * Get all property display names for a given locale.
     *
     * @param string|null $locale Locale code (defaults to app locale)
     * @return array<string, string>
     */
    public static function allPropertyDisplayNamesForLocale(?string $locale = null): array
    {
        $locale = $locale ?? app()->getLocale();
        $result = [];

        foreach (static::$localizedPropertyDisplayNames ?? [] as $property => $displayNames) {
            $result[$property] = $displayNames[$locale]
                ?? $displayNames[config('app.fallback_locale', 'en')]
                ?? $displayNames[array_key_first($displayNames) ?? 'en']
                ?? $property;
        }

        return $result;
    }
}
