<?php

namespace App\Models\OmnifyBase\Locales;

/**
 * Localized display names for Role.
 *
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by @famgia/omnify-laravel
 */
class RoleLocales
{
    /**
     * Localized display names for the model.
     *
     * @var array<string, string>
     */
    public const DISPLAY_NAMES = [
        'ja' => 'ロール',
        'en' => 'Role',
    ];

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    public const PROPERTY_DISPLAY_NAMES = [
        'slug' => [
            'ja' => 'スラッグ',
            'en' => 'Slug',
        ],
        'display_name' => [
            'ja' => '表示名',
            'en' => 'Display Name',
        ],
        'level' => [
            'ja' => 'レベル',
            'en' => 'Level',
        ],
        'description' => [
            'ja' => '説明',
            'en' => 'Description',
        ],
        'permissions' => [
            'ja' => '権限',
            'en' => 'Permissions',
        ],
    ];
}
