/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 * KHÔNG ĐƯỢC SỬA FILE NÀY!
 *
 * Auto-generated TypeScript types from Omnify schemas.
 * Any manual changes will be OVERWRITTEN on next generation.
 *
 * To modify: Edit the schema YAML file and run: npx omnify generate
 */


/**
 * Locale map for multi-language support.
 */
export interface LocaleMap {
  [locale: string]: string;
}

/**
 * Supported locales in this project.
 */
export type Locale = 'ja' | 'en';

/**
 * Validation rule with multi-locale messages.
 * Use get{Model}Rules(locale) to get Ant Design compatible rules with string messages.
 */
export interface ValidationRule {
  required?: boolean;
  type?: 'string' | 'number' | 'email' | 'url' | 'integer' | 'array' | 'object';
  min?: number;
  max?: number;
  len?: number;
  pattern?: RegExp;
  message: LocaleMap;
}

/**
 * ISO 8601 date-time string.
 */
export type DateTimeString = string;

/**
 * ISO 8601 date string (YYYY-MM-DD).
 */
export type DateString = string;
