/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 * KHÔNG ĐƯỢC SỬA FILE NÀY!
 *
 * Auto-generated TypeScript types from Omnify schemas.
 * Any manual changes will be OVERWRITTEN on next generation.
 *
 * To modify: Edit the schema YAML file and run: npx omnify generate
 */


import type { LocaleMap } from './common';

/**
 * Default locale for this project.
 */
export const defaultLocale = 'ja' as const;

/**
 * Fallback locale when requested locale is not found.
 */
export const fallbackLocale = 'en' as const;

/**
 * Supported locales in this project.
 */
export const supportedLocales = ["ja","en","vi"] as const;

/**
 * Validation messages for all supported locales.
 * Use getMessage(key, locale, params) to get formatted message.
 */
export const validationMessages = {
  "required": {
    "ja": "${displayName}は必須です",
    "en": "${displayName} is required",
    "vi": "${displayName} là bắt buộc"
  },
  "minLength": {
    "ja": "${displayName}は${min}文字以上で入力してください",
    "en": "${displayName} must be at least ${min} characters",
    "vi": "${displayName} phải có ít nhất ${min} ký tự"
  },
  "maxLength": {
    "ja": "${displayName}は${max}文字以内で入力してください",
    "en": "${displayName} must be at most ${max} characters",
    "vi": "${displayName} không được quá ${max} ký tự"
  },
  "min": {
    "ja": "${displayName}は${min}以上で入力してください",
    "en": "${displayName} must be at least ${min}",
    "vi": "${displayName} phải lớn hơn hoặc bằng ${min}"
  },
  "max": {
    "ja": "${displayName}は${max}以下で入力してください",
    "en": "${displayName} must be at most ${max}",
    "vi": "${displayName} phải nhỏ hơn hoặc bằng ${max}"
  },
  "email": {
    "ja": "有効なメールアドレスを入力してください",
    "en": "Please enter a valid email address",
    "vi": "Vui lòng nhập địa chỉ email hợp lệ"
  },
  "url": {
    "ja": "有効なURLを入力してください",
    "en": "Please enter a valid URL",
    "vi": "Vui lòng nhập URL hợp lệ"
  },
  "pattern": {
    "ja": "${displayName}の形式が正しくありません",
    "en": "${displayName} format is invalid",
    "vi": "${displayName} không đúng định dạng"
  }
} as const;

/**
 * Get validation message for a specific key and locale.
 * Supports template placeholders: ${displayName}, ${min}, ${max}, etc.
 *
 * @param key - Message key (e.g., 'required', 'minLength')
 * @param locale - Locale code (e.g., 'ja', 'en')
 * @param params - Template parameters to replace
 * @returns Formatted message string
 *
 * @example
 * getMessage('required', 'ja', { displayName: '氏名' })
 * // => '氏名は必須です'
 */
export function getMessage(
  key: string,
  locale: string,
  params: Record<string, string | number> = {}
): string {
  const messages = validationMessages[key as keyof typeof validationMessages];
  if (!messages) return key;

  let message = (messages as LocaleMap)[locale]
    ?? (messages as LocaleMap)[fallbackLocale]
    ?? (messages as LocaleMap)[defaultLocale]
    ?? key;

  // Replace template placeholders
  for (const [param, value] of Object.entries(params)) {
    message = message.replace(new RegExp(`\\$\{${param}\}`, 'g'), String(value));
  }

  return message;
}

/**
 * Get all validation messages for a specific locale.
 *
 * @param locale - Locale code
 * @returns Object with all messages for the locale
 */
export function getMessages(locale: string): Record<string, string> {
  const result: Record<string, string> = {};
  for (const [key, messages] of Object.entries(validationMessages)) {
    result[key] = (messages as LocaleMap)[locale]
      ?? (messages as LocaleMap)[fallbackLocale]
      ?? (messages as LocaleMap)[defaultLocale]
      ?? key;
  }
  return result;
}
