/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 * KHÔNG ĐƯỢC SỬA FILE NÀY!
 *
 * Auto-generated TypeScript types from Omnify schemas.
 * Any manual changes will be OVERWRITTEN on next generation.
 *
 * To modify: Edit the schema YAML file and run: npx omnify generate
 */

// Common Types
export type { LocaleMap, Locale, ValidationRule, DateTimeString, DateString } from './common';

// i18n (Internationalization)
export {
  defaultLocale,
  fallbackLocale,
  supportedLocales,
  validationMessages,
  getMessage,
  getMessages,
} from './i18n';

// Plugin Enums
export {
  BankAccountType,
  BankAccountTypeValues,
  isBankAccountType,
  getBankAccountTypeLabel,
  getBankAccountTypeExtra,
} from '@omnify-client/enum/BankAccountType';
export {
  Prefecture,
  PrefectureValues,
  isPrefecture,
  getPrefectureLabel,
  getPrefectureExtra,
} from '@omnify-client/enum/Prefecture';
export {
  PrefectureCode,
  PrefectureCodeValues,
  isPrefectureCode,
  getPrefectureCodeLabel,
  getPrefectureCodeExtra,
} from '@omnify-client/enum/PrefectureCode';

// Models (with Zod schemas, i18n, and Create/Update types)
export type { User, UserCreate, UserUpdate } from './User';
export {
  userSchemas,
  userCreateSchema,
  userUpdateSchema,
  userI18n,
  getUserLabel,
  getUserFieldLabel,
  getUserFieldPlaceholder,
} from './User';
export type { Permission, PermissionCreate, PermissionUpdate } from './Permission';
export {
  permissionSchemas,
  permissionCreateSchema,
  permissionUpdateSchema,
  permissionI18n,
  getPermissionLabel,
  getPermissionFieldLabel,
  getPermissionFieldPlaceholder,
} from './Permission';
export type { Role, RoleCreate, RoleUpdate } from './Role';
export {
  roleSchemas,
  roleCreateSchema,
  roleUpdateSchema,
  roleI18n,
  getRoleLabel,
  getRoleFieldLabel,
  getRoleFieldPlaceholder,
} from './Role';
export type { RolePermission, RolePermissionCreate, RolePermissionUpdate } from './RolePermission';
export {
  rolePermissionSchemas,
  rolePermissionCreateSchema,
  rolePermissionUpdateSchema,
  rolePermissionI18n,
  getRolePermissionLabel,
  getRolePermissionFieldLabel,
  getRolePermissionFieldPlaceholder,
} from './RolePermission';
export type { Team, TeamCreate, TeamUpdate } from './Team';
export {
  teamSchemas,
  teamCreateSchema,
  teamUpdateSchema,
  teamI18n,
  getTeamLabel,
  getTeamFieldLabel,
  getTeamFieldPlaceholder,
} from './Team';
export type { TeamPermission, TeamPermissionCreate, TeamPermissionUpdate } from './TeamPermission';
export {
  teamPermissionSchemas,
  teamPermissionCreateSchema,
  teamPermissionUpdateSchema,
  teamPermissionI18n,
  getTeamPermissionLabel,
  getTeamPermissionFieldLabel,
  getTeamPermissionFieldPlaceholder,
} from './TeamPermission';
