/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 * KHÔNG ĐƯỢC SỬA FILE NÀY!
 *
 * Auto-generated TypeScript types from Omnify schemas.
 * Any manual changes will be OVERWRITTEN on next generation.
 *
 * To modify: Edit the schema YAML file and run: npx omnify generate
 */

// Common Types
export type { LocaleMap, Locale, ValidationRule, DateTimeString, DateString } from './common';

// i18n (Internationalization)
export {
  defaultLocale,
  fallbackLocale,
  supportedLocales,
  validationMessages,
  getMessage,
  getMessages,
} from './i18n';

// Plugin Enums
export {
  BankAccountType,
  BankAccountTypeValues,
  isBankAccountType,
  getBankAccountTypeLabel,
  getBankAccountTypeExtra,
} from '../enum/plugin/BankAccountType';
export {
  Prefecture,
  PrefectureValues,
  isPrefecture,
  getPrefectureLabel,
  getPrefectureExtra,
} from '../enum/plugin/Prefecture';
export {
  PrefectureCode,
  PrefectureCodeValues,
  isPrefectureCode,
  getPrefectureCodeLabel,
  getPrefectureCodeExtra,
} from '../enum/plugin/PrefectureCode';

// Models (with Zod schemas, i18n, and Create/Update types)
export type { User, UserCreate, UserUpdate } from './User';
export {
  userSchemas,
  userCreateSchema,
  userUpdateSchema,
  userI18n,
  getUserLabel,
  getUserFieldLabel,
  getUserFieldPlaceholder,
} from './User';
